term.Add('DataNotLoaded', 'ВАШИ ДАННЫЕ НЕ ЗАГРУЖЕНЫ. ПОЖАЛУЙСТА, ПОДОЖДИТЕ. ЕСЛИ ЭТО СЛУЧИТСЯ СНОВА, ПОЖАЛУЙСТА, СООБЩИТЕ НАМ ОБ ЭТОМ!')
term.Add('UnknownError', 'Произошла неизвестная ошибка.')

term.Add('+Money', '+$#')
term.Add('-Money', '-$#')
term.Add('InvalidArg', 'Недействительный аргумент.')
term.Add('CantFindPlayer', 'Невозможно найти игрока #.')
term.Add('CannotAfford', 'Вы не можете себе это позволить!')
term.Add('Bankrupt', 'Вы обанкротились! Вся ваша собственность была распродана.')
term.Add('TargetCannotAfford', '# не может себе это позволить!')
term.Add('NeedVIP', 'Вам нужен VIP статус! Напишите /upgrades чтобы купить.')
term.Add('NeedToWait', 'Вам нужно подождать # секунд чтобы сделать это!')
term.Add('ChangeJob', '# теперь # #.')
term.Add('CannotChangeJob', 'Вы не можете сменить работу в течении #!')
term.Add('ChangeName', '# изменил имя на #')
term.Add('ChangeNameReserved', 'Name changed! Your old name is reserved for 24h, after that anyone may take it.')
term.Add('Welfare', 'Социальная выплата! Вы получили $# и потеряли # кармы.')
term.Add('WelfareTaxed', 'Социальная выплата! Вы получили $#, и заплатили $# за налог на собственность, а так же потеряли # кармы.')
term.Add('WelfareMissed', 'Вы не получили социальную выплату из-за нахождения под арестом!')
term.Add('PropertyTax', 'Вы заплатили # за налог на собственность и получили # кармы.')
term.Add('NotAllowedInSpawn', '# недопустимо на спавне!')
term.Add('GainedKarmaDrop', 'Вы получили # кармы за игру на сервере. Вы получите ещё # через 15 минут.')
term.Add('LostKarma', 'Вы потеряли # кармы за #!')
term.Add('LostKarmaNR', 'Вы потеряли # кармы.')
term.Add('LostKarmaDrugs', 'Вы потеряли # кармы за использование наркотиков.')
term.Add('EarnedKarmaHealing', 'Вы получили 5 кармы за хорошую работу медиком.')
term.Add('DrugOverdose', 'Your family will not mourn the death of a filthy junky like you.')
term.Add('DrugAids', 'You\'ve contracted aids due to your drug use')
term.Add('SpawnPropsSoFast', 'Пожалуйста не спавните пропы так быстро.')
term.Add('RPNameShort', 'Имя должно быть длиннее # символов.')
term.Add('RPNameLong', 'Имя должно быть короче # символов.')
term.Add('CannotRPName', 'Вы не можете сменить ваше имя.')
term.Add('RPNameUnallowed', 'Ваше имя содержит запрещённые символы (#).')
term.Add('SteamRPNameTaken', 'Your Steam name is already being used as someone\'s RP name, so we put a "1" after your name.')
term.Add('RPNameTaken', 'Это имя уже занято')
term.Add('EscapeDemotion', 'You tried to escape demotion. You failed, and have been demoted.')
term.Add('PlayerDemotedBy', '# has been demoted by # for #')
term.Add('PlayerDemoted', '# has been demoted.')
term.Add('PlayerNotDemoted', '# has not been demoted.')
term.Add('DemotionStarted', '# has started a demotion vote for #.')
term.Add('DemoteCooldown', 'You must wait # more seconds before starting another demotion vote.')
term.Add('YouDemotedX', 'You have demoted #.')
term.Add('DemotionReason', 'Please give a reason to demote.')
term.Add('DemoteReasonLong', 'Your demote reason must be below # characters.')
term.Add('DemoteSelf', 'You cannot demote yourself.')
term.Add('DemoteYouStarted', '# started a demotion vote on you for: #')
term.Add('UnableToDemote', 'You cannot call a demote on this team.')
term.Add('ChannelLimit', 'Выберите канал между 0 и 100.')
term.Add('ChannelSet', 'Канал изменён на #.')
term.Add('ChannelNotSet', 'Вы не настроили свой канал!')
term.Add('GiveMoneyLimit', 'Нельзя передать меньше чем $1.')
term.Add('DropMoneyLimit', 'Нельзя выбросить меньше чем $1.')
term.Add('ChequeArg1', 'Недействительный аргумент #1: получатель.')
term.Add('ChequeArg2', 'Недействительный аргумент #2: сумма.')
term.Add('PlayerGaveCash', '# передал вам #.')
term.Add('PlayerSentWire', 'Вы перечислили # # с учётом налогов.')
term.Add('PlayerGotWire', '# перечислил вам #.')
term.Add('YouGaveCash', 'Вы передали # #.')
term.Add('MustLookAtPlayer', 'Вы должны смотреть на игрока.')
term.Add('CantWhileRestrained', 'Вы не можете сделать это пока вы связанны.')
term.Add('ClassNoWeaponKnowledge', 'Your class lacks the knowledge to use this weapon.')
term.Add('CantDropCarrierNoRoom', 'There is no room to drop your hostage here.')
term.Add('CantEscapeCarrierNoRoom', 'There\'s no room to escape! Keep struggling to injure your captor!')
term.Add('CantZiptieDistance', 'Your target is too far away now.')
term.Add('CutZiptieWithKnife', 'You must use a knife to cut zipties!')
term.Add('UpgradedSkill', 'Навык # улучшен до # уровня.')
term.Add('BoughtKarma', 'Приобретено # Кармы за #')

term.Add('CannotMaterialThisWeapon', 'Вы не можете изменить материал этого оружия!')
term.Add('SetWepMaterial', 'Материал оружия изменён!')

term.Add('HoesProfit', 'Вы получили $100 от ваших шлюх.')
term.Add('CannotAffordHoe', '# не может позволить себе ваши услуги!')
term.Add('YouCannotAffordHoe', 'Вы не можете позволить себе услуги #!')
term.Add('GetCloser', 'Вы должны быть ближе к вашей цели!')
term.Add('YouAreDead', 'Вы мертвы!')
term.Add('NotAHoe', 'Вы не шлюха.')
term.Add('NPCsDontFuck', 'Вы не можете переспать с NPC.')
term.Add('TargetFrozen', 'Ваша цель заморожена.')
term.Add('WaitingForAnswer', 'Ождание ответа.')
term.Add('TargetWontFuck', 'Ваша цель не желает использовать ваши услуги.')
term.Add('TargetTooFar', 'Ваша цель слишком далеко.')
term.Add('HoeTooFar', 'Ваша шлюха сликом далеко.')
term.Add('+FuckCostPimp', '+ $# - 100 (Доля сутенёра)')

term.Add('Warranted', '#\nПричина: #\nЗапрошено: #.')
term.Add('Wanted', '#\nПричина: #\nЗапрошено: #.')
term.Add('UnWanted', '#\nЗапрошено: #.')
term.Add('CannotUnwant', 'Вы не можете убрать из розыска неразыскиваемого игрока!')
term.Add('Arrested', '# был арестован.')
term.Add('UnArrested', '# был выпущен из тюрьмы.')
term.Add('YouWanted', 'Вы объявили в розыск #')
term.Add('YouUnwanted', 'Вы убрали из розыска #')

term.Add('DoorLocked', 'Закрыто!')
term.Add('DoorUnlocked', 'Открыто!')
term.Add('TeamCannotOwnProperty', 'Ваша профессия не может владеть собственностью.')
term.Add('PlayerTeamCannotOwnProperty', '# не может владеть собственностью.')
term.Add('PlayerPropertyAlreadyOwned', '# уже владеет собственностью.')

term.Add('PropertyAlreadyOwned', 'Вы уже владеете собственностью! Продайте её перед покупкой новой.')
term.Add('PropertyBought', 'Вы приобрели # за # и получили # кармы.')
term.Add('PropertySold', 'Вы продали # за #.')
term.Add('PropertySetTitle', 'Вы изменили имя собственности на #')
term.Add('PropertyNoneLeft', 'У вас нет собственности на продажу!')
term.Add('PropertyCoOwnerVotePending', '# уже имеет приглашение на совладение этой собственностью!')
term.Add('PropertyCoOwnerAdded', '# был приглашён стать совладельцем собственности #.')
term.Add('PropertyCoOwnerAddedYou', '# пригласил вас стать совладельцем собственности #.')
term.Add('PropertyCoOwnerRemoved', '# был удалён из собственности #.')
term.Add('PropertyCoOwnerRemovedYou', '# удалил вас из собственности #.')
term.Add('PropertOrDEnabled', 'Org access for # enabled.')
term.Add('PropertOrgDisabled', 'Org access for # disabled.')

term.Add('HotelTennantNotInRange', '# is too far away!')
term.Add('HotelTennantAdded', 'Added # to #')
term.Add('HotelTennantAddedYou', 'You have rented #.')
term.Add('HotelTennantDeclined', '# has declined to rent #.')
term.Add('HotelTennantAdded', 'Added # to #.')
term.Add('HotelTennantEvicted', 'You have evicted # from #.')
term.Add('HotelTennantEvictedYou', 'You have been evicted from #.')
term.Add('HotelTenantBankrupt', '# is bankrupt and can no longer afford your hotel room!')
term.Add('HotelPay', '# has paid # for their hotel room.')

term.Add('EventEnded', '# эвент закончился.')

-- Orgs
term.Add('OrgDisbanded', '# has been disbanded!')
term.Add('OrgPlayerKicked', '# has been kicked from #.')
term.Add('OrgPlayerYoureKicked', 'You have been kicked from #.')
term.Add('OrgMustLeaveFirst', 'You need to leave your current organization to create a new one.')
term.Add('OrgNameShort', 'Please make your organization name longer than 2 characters.')
term.Add('OrgNameLong', 'Please make your organization name shorter than 20 characters.')
term.Add('OrgNameTaken', 'This name is already taken. Please choose another!')
term.Add('OrgCannotAfford', 'You cannot afford to create an organization.')
term.Add('OrgCreated', 'You have successfully created your organization.')
term.Add('OrgMOTDChanged', '#\'s MoTD has been updated.')
term.Add('OrgColorChanged', 'You\'ve changed your organization color.')
term.Add('OrgPlayerQuit', '# has quit #!')
term.Add('OrgMemberLimit', 'You\'ve reached the limit of # org members!')
term.Add('OrgMemberJoined', '# has joined #.')
term.Add('OrgBankBusy', 'Somebody else is currently using the org bank. Wait a moment!')
term.Add('OrgBankFull', 'The org bank cannot exceed #!')
term.Add('OrgBankCannotAfford', 'The org bank contains insufficient funds for that.')
term.Add('OrgBankDeposited', 'You\'ve deposited # into the org bank (# has been taxed)')
term.Add('OrgBankInsufficient', 'The org bank cannot afford to withdraw that much!')
term.Add('OrgBankWithdrawn', 'You\'ve withdrawn # from the org bank.')
term.Add('OrgOwnershipTransferred', 'You\'ve transferred ownership of # to #.')
term.Add('OrgOwnershipTransferredYou', '# has transferred ownership of # to you.')
term.Add('OrgRenameFailed', 'Rename failed for some reason. Maybe that name was taken?')
term.Add('OrgRenamed', '# has been renamed to #.')
term.Add('OrgDisbandedBankReturned', '#\'s bank balance of $# has been returned to you.')
term.Add('OrgRankNameLength', 'Your rank must have a name.')
term.Add('OrgRankNameTaken', 'This rank name is already in use.')
term.Add('OrgTooManyInvites', 'This player has too many pending invites.')
term.Add('OrgInvitedAlready', 'This player already has a pending invitation to #.')

term.Add('MustBeNearbyMayorMachine', 'Вы должны быть перед компьютером в вашем офисе!')
term.Add('MustBeMayorSetLaws', 'Вы должны быть мэром для изменения законов!')
term.Add('MustBeMayorResetLaws', 'Вы должны быть мэром для обнуления законов!')
term.Add('LawsTooLong', 'Ваши законы слишком длинные!')
term.Add('AgendaTooLong', 'Ваша агенда слишком длинная!')
term.Add('LotteryTax', 'Вы получили # из налогов с лотереи.')
term.Add('LotteryWinner', '# выиграл # в лотерею!')
term.Add('NoLottery', 'Никто другой не принял участия в лотерее, ваши деньги были возвращены.')
term.Add('NoLotteryTax', 'Вы получили $0 из налогов с лотереи, так как никто не принял участия.')
term.Add('NotInLottery', 'Вы не приняли участия в лотерее.')
term.Add('InLottery', 'Вы учавствуете в лотерее на #.')
term.Add('NoLotteryAll', 'Никто другой не принял участия в лотерее.')
term.Add('CannotLottery', 'Вы не можете начать лотерею прямо сейчас.')
term.Add('LottoCost', 'Пожалуйста укажите стоимоть участия в лотерее ($#-$#).')
term.Add('LotteryStarted', 'Началась лотерея!')

term.Add('LockdownStarted', 'Мэр объявил начало комендатского часа. Пожалуйста вернитесь домой!')
term.Add('CannotUnlockdown', 'Вы не можете закончить комендантский час прямо сейчас.')
term.Add('LockdownEnded', 'Комендантский час закончился.')
term.Add('LawsChanged', 'Законы были изменены!')

term.Add('WarrantExpired', 'Ваш ордер на обыск истёк.')
term.Add('PlayerIsPoliceWant', 'Вы не можете объявить в розыск #. Увольте его за коррупцию.')
term.Add('PlayerIsPoliceWarrant', 'Вы не можете запросить ордер на обыск #. Увольте его за коррупцию.')
term.Add('PlayerCannotBeWanted', '# не может быть объявлен в розыск!')
term.Add('PlayerAlreadyWanted', '# уже в розыске!')
term.Add('PlayerAlreadyWarranted', 'У вас уже есть ордер на обыск #!')
term.Add('PlayerNotWanted', '# не разыскивается!')
term.Add('PlayerNotWarranted', 'У вас нет ордера на обыск #!')
term.Add('MustTargetPlayerWithWarrant', 'Вам нужен ордер на обыск чтобы проникнуть на базу!')
term.Add('WarrantRequestAcc', 'Ваш ордер на обыск истёк.')
term.Add('WantReasonTooLong', 'Причина розыска слишком длинная! Максимум 40 символов!')

term.Add('HitComplete', 'Заказ на # завершён.')
term.Add('HitKindaFailed', 'Возникло некоторое недопонимание, и вы заказали самого себя.')
term.Add('YourHitComplete', 'Вы были убиты наёмным убийцей.')
term.Add('CantHitYourself', 'Вы не можете заказть самого себя!')
term.Add('CantPlaceHit', 'Наёмный убийца не может создавать заказы!')
term.Add('CantPlaceHitGrace', 'Вы не можете заказть мэра пока действует неприкосновенность!')
term.Add('HitPriceLimit', 'Цена заказа должна быть между # и #.')
term.Add('HitTimer', 'Вы не можете заказать убийство еще # секунд.')
term.Add('MultiHit', 'Вы не можете заказать одного и того же человека два раза подряд!')
term.Add('HitCooldown', 'Этого игрока уже заказывали недавно.')
term.Add('BountyIncrease', 'Вы повысили награду за # на #.')
term.Add('HitPlaced', 'Вы заказали убийство # за #.')
term.Add('HitmanFailed', 'Вы не справились со своей работой наёмного убийцы!')
term.Add('HitmanKilledAll', 'Это ваш удачный день! Этот киллер нёс награду, которая была у вас на голове.')
term.Add('Need911Reason', 'Пожалуйста введите причину почему вы хотите позвонить в 911!')
term.Add('Canceled911', 'Вы отменили ваш 911 звонок.')

term.Add('EmployeeChangedJob', 'Ваш работник сменил профессию!')
term.Add('EmployeeChangedJobYou', 'Вы разорвали контракт со своим работником, потому, что вы сменили профессию.!')
term.Add('EmployeeLeft', 'Ваш работник вышел из сервера!')
term.Add('PlayerNotHirable', '# не нанимаемый рабочий.')
term.Add('EmployeeTriedEmploying', 'Вы сами являетесь наёмный работником, вы не можете никого нанимать!')
term.Add('AlreadyEmployed', 'Вы уже наняты!')
term.Add('CannotAffordEmployee', 'Вы не можете позволить себе нанять работника!')
term.Add('EmployRequestSent', 'Предложение о трудоустройстве было отправленно #.')
term.Add('SetHirePriceToHigh', 'Вы не можете нанять работника на зарплату больше, чем #!')
term.Add('SetHirePrice', 'Вы установили зарплату работника на #.')
term.Add('YouHired', 'Вы наняли # за #.')
term.Add('YouAreHired', '# нанял вас за #.')
term.Add('EmployRequestDen', '# отказался от вашего предложения о трудоустройстве.')
term.Add('EmployeeFired', 'Вы уволили #.')
term.Add('EmployeeFiredYou', '# уволил вас!')
term.Add('EmployeeQuit', '# ушел с вашей работы!')
term.Add('EmployeeQuitYou', 'Вы ушли с работы, получив #.')

term.Add('CannotTool', 'Ваш ранг не может использовать инструмент "#"!')
term.Add('DupeRestrictedEnts', 'You cannot spawn dupes containing these entities!')
term.Add('DupeNeedsRepair', 'Your dupe has blacklisted models are entities in and will likely be broken. Click again within 5 seconds to paste it anyway.')
term.Add('DupeRemovedModel', '# blacklisted props and # constraints have been removed from your dupe.')
term.Add('WhitelistFull', 'The whitelist is full #/750')
term.Add('CacheFull', 'The model precache is full #/100!')
term.Add('PropWhitelisted', '# has been whitelisted by #.')
term.Add('PropBlacklisted', '# has been blacklisted by #.')
term.Add('UnsharedPropsYou', 'You have unshared your props with #.')
term.Add('UnsharedProps', '# has unshared their props with you.')
term.Add('OrgSharedProps', '# has shared their props with the org.')
term.Add('OrgUnsharedProps', '# has unshared their props with the org.')
term.Add('SharedPropsYou', 'You have shared your props with #.')
term.Add('SharedProps', '# has shared their props with you.')
term.Add('PPGroupSet', '# has been set to group # by #.')
term.Add('PropNotWhitelisted', '# не в вайтлисте!')

term.Add('CannotDestroyWeapon', 'Вы не можете уничтожить это оружие!')

term.Add('YourEntDestroyed', 'Ваш # был уничтожен!')
term.Add('InvalidURL', 'Недействительный URL!')
term.Add('VideoFailed', 'Не удалось загрузить видео: #.')
term.Add('VideoTooLong', 'You cannot play videos over # minutes!')
term.Add('FoodLimitReached', 'Вы достигли лимита еды!')
term.Add('BoughtFoodProduction', 'Вы заплатили # за продукты.')
term.Add('SoldFoodNoProf', 'Вы продали еду и не получили денег.')
term.Add('SoldFood', 'Вы продали еду и заработали #.')
term.Add('BoughtFood', 'Вы купили еду для #.')
term.Add('MicrowaveFoodType', 'Продукт микроволновки изменён на #')
term.Add('ThereIsACook', 'Есть повар. Вы не можете сделать этого!')
term.Add('EmptyShipment', 'В коробке нет товаров!')

term.Add('GCMessageLimit', 'Ваше сообщение должно быть длиннее чем 1 символ!')

term.Add('CantSuicideJail', 'Вы не можете покончить жизнь самоубийством в тюрьме.')
term.Add('CantSuicideWanted', 'Вы не можете покончить жизнь самоубийством пока вы в розыске.')
term.Add('CantSuicideFrozen', 'Вы не можете покончить жизнь самоубийством пока вы заморожены.')
term.Add('CantSuicideLiveFor', 'Вам ещё слишком долго жить!')
term.Add('CantSuicideRestrained', 'You can\'t suicide while restrained.')
term.Add('YouSuicided', 'Вы потеряли 5 кармы за позор вашей семьи.')

term.Add('CantPurchaseUpgrade', 'Вы не можете купить это. #')

term.Add('RPItemBought', 'Вы приобрели # за #.')
term.Add('RPItemBoughtLimit', 'Вы приобрели #/# # за #.')

term.Add('CantAdminCleanup', 'Вы не можете использовать админскую очистку карты!')

term.Add('MayorHasDied', 'Мэр погиб!')
term.Add('YouWereBailed', '# внёс за вас залог!')

term.Add('AmmoLabProfit', 'You received $# from your ammo lab.')
term.Add('BoughtAmmo', 'You have bought ammo for $#.')
term.Add('AmmoLabExploded', 'Your ammo lab has exploded!')

term.Add('ArmorLabProfit', 'You received $# from your armor lab.')
term.Add('BoughtArmor', 'You have bought armor for $#.')
term.Add('ArmorLabExploded', 'Your armor lab has exploded!')

term.Add('ChequeFound', 'You have found # in a cheque made out to you from #.')
term.Add('ChequeMadeTo', 'This cheque is made out to #.')
term.Add('ChequeTorn', 'You have torn up the cheque.')
term.Add('MoneyFound', 'Вы нашли $#!')

term.Add('MustBeHobo', 'Вы должны быть бомжом что бы использовать это!')
term.Add('AlreadyDisguised', 'Вы уже замаскированы!')
term.Add('GunLicenseActive', 'Вы получили лицензию на оружие.')
term.Add('AlreadyHasGunLicense', 'Вы уже имеете лицензию на оружие!')
term.Add('YouGotAIDS', 'Вы заразились СПИДом и скоро умрете.')
term.Add('YouGotHIV', 'Вы заразились ВИЧем от контакта с иглой.')
term.Add('STDCured', 'Вы вылечили свою вeнерические заболевания.')
term.Add('PimpSTDCured', 'Вы вылечели # от их вeнерических заболеваний.')
term.Add('NowDisguised', 'Вы теперь замаскированны как #.')
term.Add('DisguiseWorn', 'Ваша маскировка изнасилась.')
term.Add('DisguiseLimit', 'Вы не можете маскироватся ближайшие # минут.')

term.Add('MedLabProfit', 'Вы получили $# от вашей мед лаборатории.')
term.Add('BoughtHealth', 'Вы вылечились за $#.')
term.Add('MedLabExploded', 'Your medic lab has exploded!')

term.Add('KeypadControlsX', 'This keypad controls # entities.')
term.Add('EntityControlledByX', 'This entity is controlled by # keypads.')

term.Add('VoteAlone', 'Вы выиграли выборы, так как вы единственный на сервере, жалко...')
term.Add('BannedFromJob', 'Вам запрещена профессия #s. Причина: #.')
term.Add('BannedFromJobPerma', 'You are restricted from that job. Reason: #.')
term.Add('CantGoPolice', 'Вас недавно убили. Вы должны подождать # секунд перед темЮ как стать полицейским.')
term.Add('VotedTooSoon', 'Пожалуйста подождите # секунд перед тем как собиратся взять это профессию.')
term.Add('AlreadyThisJob', 'You\'re already this job!')
term.Add('JobLimit', 'Слишком много игроков этой профессии.')
term.Add('RegisteredForVote', 'Вы зарегистрировались на ближайшие выборы!')
term.Add('AlreadyVoting', 'Выборы уже начались. Вы опоздали!')
term.Add('AdminRoomNotSet', 'The sit room location has not been set!')
term.Add('JobNeedsPlaytime', 'Вы должны отыграть # часов или купить вип, что бы взять это профессию!')
term.Add('JobNeedsAdmin', 'Вы должны быть модератором или выше для этой профессии.')
term.Add('JobNeedsSA', 'You must be SA+ for this job.')
term.Add('JobNeedsBanned', 'You need to be banned from the server to become this class.')
term.Add('JobNeedsManualSet', 'You need to be set to this job by an admin.')
term.Add('IncorrectJob', 'You are not currently the correct job to do that!')
term.Add('VoteStarted', 'Голосование создано.')
term.Add('CannotJob', 'Вы не можете сменить свою профессию прямо сейчас.')
term.Add('JobLenShort', 'Название профессии должно быть больше # символов.')
term.Add('JobLenLong', 'Название профессии должно быть больше # символов.')

term.Add('CannotPurchaseItem', 'Вам не дозволено покупать этот предмет.')
term.Add('ItemUnavailable', 'Этот предмет не доступен.')
term.Add('UnableToItem', 'Неудалось купить этот предмет.')
term.Add('ShipmentCooldown', 'Пожалуйста, подождите перед тем, как покупать еще один ящик.')

term.Add('MedicExists', 'Вы не можете покупать лечение, если на сервере присутствует медик.')
term.Add('HealthIsFull', 'Вы уже здоровы!')

term.Add('CannotDropWeapon', 'Вы не можете выкинуть это оружие!')
term.Add('LookAtEntity', 'Вы должны смотреть на энтити!')
term.Add('CannotSetPrice', 'Вы не можете устанавливать цену этому предмету!')

term.Add('AnalProlapse', 'Вы умерли от разрыва очка.')
term.Add('NoMorePoo', 'У вас закончилось говно!')
term.Add('NotARapist', 'Вы не насильник.')
term.Add('RapeSOD', 'Вы не можете изнасиловать админа.')
term.Add('RapeFailed', 'У вас не получилось изнасиловать!')
term.Add('RapeAttempted', 'Кто-то попытался вас изнасиловать.')
term.Add('Raped', 'Вы вошли в #.')
term.Add('YouAreRaped', 'Кто-то насилует вас.')
term.Add('AnalProlapseShort', 'Ваше очко порвалось.')
term.Add('DickFellOff', 'Ваш дружок отвалился.')
term.Add('NoRangeOfMotion', 'У вас нет особого пространства что-бы совершать такие движения.')
term.Add('RapeStruggled', 'Вы смогли выбратся от насильника!')
term.Add('RapeVictimStruggled', 'Ваша жертва сбежала!')

term.Add('CannotVote', 'Вы не можете голосовать.')
term.Add('FoundNothing', 'Вы ничего не нашли.')
term.Add('RobberyAttempt', 'Вы чувствуете лёгкое движение в ваших карманах.')
term.Add('YouRobbed', 'Вы украли $#!')
term.Add('YouAreRobbed', 'Ваш кошелёк стал легче.')
term.Add('YouRobbedItem', 'Вы украли предмет. Берите его быстрее!')
term.Add('YouAreRobbedItem', 'Ваши карманы стали легче.')

term.Add('NoteUpdated', 'Текст записки обновлён.')
term.Add('USENote', 'Используйте E чтобы изменить текст записки.')

term.Add('OrgYouAreStuck', 'Вы застряли! >:)')
term.Add('OrgYourRank', '# установил ваш ранг на \'#\'.')
term.Add('OrgSetRank', '# стал \'#\'.')
term.Add('OrgUnknownRank', 'Неизвестный ранг \'#\'.')
term.Add('OrgRankRename', 'Ранг \'#\' был переименован \'#\'.')
term.Add('OrgReorderLimit', 'Вы не можете пересортировать ранги.')
term.Add('OrgRankUpdated', 'Ранг \'#\' был обновлён.')
term.Add('OrgMaxRanks', 'Достигнуто максимальное количество рангов.')
term.Add('OrgRankCreated', 'Ранг \'#\' был создан.')
term.Add('OrgDeleteLimit', 'Вы не можете удалять высшие и низшие ранги.')
term.Add('OrgRankDelete', 'Ранг \'#\' был удален.')
term.Add('OrgBannerUpdated', 'Баннер обновлен.')
term.Add('OrgPlayerInvited', 'Вы пригласили # за $#.')

term.Add('SetOutfit', 'Ваша одежда была установлена на #')

-- Stools
term.Add('CantMetagameKeypad', 'You must use a keypad for your fading door!')
term.Add('FadeDoorCreated', 'Fading door создан.')
term.Add('FadeDoorCreatedExtra', 'Fading door создан. Теперь, нажмите правой кнопкой мыши чтобы поставить кейпад.')
term.Add('InvalidPassword', 'Неверный пароль!')
term.Add('KeypadHoldLength', 'The hold length must be at least # seconds.')
term.Add('NoCollidedWorld', 'Коллизия мира отключена.')
term.Add('CollidedWorld', 'Коллизия мира включена.')
term.Add('NoCollided', 'Коллизия выключена.')
term.Add('Collided', 'Коллизия включена.')
term.Add('UnBreakable', 'Неуязвимость включена.')
term.Add('Breakable', 'Неуязвимость выключена.')
term.Add('ColorizedYou', 'Ваш цвет был изменён.')
term.Add('DecolorizedYou', 'Ваш цвет был сброшен')
term.Add('ColorizedPlayer', 'Перекрашен #.')
term.Add('DecolorizedPlayer', 'Сброшен цвет у #.')
term.Add('DecolorizedAll', 'Сброшен цвет у всех.')
term.Add('FadingDoorAdded', 'Проп соеденён с fading door.')
term.Add('FadingDoorRemoved', 'Проп отсоединён от fading door.')
term.Add('FadingDoorOnlyProps', 'Только пропы могут становиться fading door!')
term.Add('FadingDoorMaxProps', 'Вам разрешено делать только # пропов в однин fading door')
term.Add('FadingDoorNoProps', 'Нажмите правую кнопку мыши для указания fading door пропов, прежде чем создавать кейпад!')

-- Sandbox
term.Add('SboxXLimit', 'Вы достигли лимита # #!')
term.Add('SboxSpawned', 'Заспавнено #/# #.')

-- Entities folder
term.Add('ImageNSFW', 'Эта картинка была отмечена как непотребная. Пожалуйста используйте другую.')

term.Add('PlayerTaserResistance', '# получил неприкосновенность и на этот раз не пострадал от электрошокера!')
term.Add('PlayerTaserResistanceSelf', 'Вы были поражены электрошоком, но получили неприкосновенность и на этот раз не пострадали!')

term.Add('ArcadeMachineUse', 'Get ready to play!')
term.Add('PlayerNotInJail', '# не в тюрьме.')
term.Add('PlayerFuckedBailing', 'Ты придурок, копы уже у тебя на хвосте!')
term.Add('PlayerBailedPlayer', 'Вы внесли залог за # в размере # и получили # кармы.')
term.Add('PlayerTookDonationBox', 'Вы забрали #.')
term.Add('YouDontOwnThis', 'Вы не владеете этим!')
term.Add('PlayerReceivedDonationBox', 'Кто-то положил # в вашу коробку для пожертвований.')
term.Add('PlayerNotWanted', 'Этот игрок не в розыске!')
term.Add('PlayerTookMoneyBasket', 'Вы забрали #.')
term.Add('PrinterIsFull', 'Этот принтер уже заправлен!')
term.Add('PrinterRefilled', 'Вы заправили принтер за #.')
term.Add('PlayerSoldDrugs', 'Вы продали # за #.')

term.Add('SoldItem', 'Вы продали предмет заработав # и получив # кармы.')
term.Add('BoughtItem', 'Вы приобрели предмет за #.')

term.Add('GamblingMachinePlayerCannotAfford', 'Вы не можете позволить себе игру в #!')
term.Add('GamblingMachineHouseCannotAfford', 'Вы не можете позволить себе ваш #! Автомат был выключен.')
term.Add('GamblingMachineOwnerCannotAfford', 'The owner of this # machine can no longer afford to operate. It is now out of service.')
term.Add('GamblingMachineInService', 'Ваш автомат # теперь включён.')
term.Add('GamblingMachineIOutService', 'Ваш автомат # теперь выключен.')

term.Add('5050PlayerWin', 'Вы выиграли # играя в FiftyFifty!')
term.Add('5050PlayerLose', 'Вы проиграли # играю FiftyFifty!')
term.Add('5050Tie', 'Выпала ничья, и никто не выиграл.')

term.Add('BasicSlotsPlayerWin', 'Вы выиграли # играя Basic Slots!')
term.Add('BasicSlotsPlayerLose', 'Вы проиграли # играя Basic Slots!')

term.Add('SpinWheelPlayerWin', 'Вы выиграли # играя Spin Wheel!')
term.Add('SpinWheelPlayerLose', 'Вы проиграли # играя Spin Wheel!')

term.Add('AlreadyHaveWeapon', 'У вас уже есть это оружие, лучше уберите его в карман.')

term.Add('BiometricAddedAccess', 'Added # to scanner')
term.Add('BiometricRemovedAccess', 'Removed # from scanner')
term.Add('BiometricToggledOrgOwn', 'Toggled org ownership')
term.Add('BiometricCopiedSettings', 'Copied settings to # scanners')

term.Add('TollMadeProfit', 'Вы заработали # (# было налогообложено) с toll\'a.')

term.Add('YourItemLabRanOut', 'Предметы в вашей вещевой лаборатории закончились!')

-- Weapons folder
term.Add('ArrestBatonBonus', 'Вы получили # бонус и # кармы за уничтожение нелегального предмета.')
term.Add('ArrestBatonArrested', 'Вы были арестованы сотрудником #.')
term.Add('ArrestBatonYouArrested', 'Вы арестовали #.')
term.Add('PlayerRangDoorbell', 'Кто-то постучался в вашу дверь.')
term.Add('KeysCooldown', 'The lock on this door is busted! Try again in # seconds!')
term.Add('UnarrestBatonTarg', 'Вы выпустили из тюрьмы за #.')
term.Add('UnarrestBatonOwn', 'Вы выпустили # из тюрьмы.')

term.Add('ApparelPurchased', 'Вы купили # за #.')
term.Add('ApparelEquiped', '# одето!')
term.Add('ApparelRemoved', '# снято!')

term.Add('BURGHungerImmune', 'You\'re immune to hunger until you die, now!')
term.Add('BURGNotPeople', 'Silly burger, burgers aren\'t people!')

term.Add('CannotPocket', 'Вы не можете положить # в ваш карман!')
term.Add('CannotPocketCooldown', 'Вы должны подождать # секунд, для того что бы положить это в карман!')
term.Add('CannotPocketUsedShipments', 'Merchant classes cannot pocket partially full shipments!')

-- Kombat
term.Add('KombatFull', 'Все места комбата уже заняты, как же жаль.')
term.Add('KombatMissedDeadline', 'Вы не успели записатся на комбат.')
term.Add('KombatRestrained', 'Вы не можете участвовать в комбате, пока вы связаны.')
term.Add('KombatCarrying', 'Sorry, you cannot enter Kombat while carrying someone.')

-- Gun Lab
term.Add('ItemLabRefilled', 'Вы заполнили лабораторию за $#. Теперь в ней # металла.')
term.Add('ItemLabCrafting', 'Вы использовали # метала что бы начать создавать #.')

-- Bodygroups
term.Add('ModelNoBodyGroups', 'This model does not contain any preset bodygroups.')
term.Add('BodyGroupPermission', 'You do not have permission to set bodygroups on this model/player.')
term.Add('BodyGroupNotFound', 'The bodygroup "#" was not found for this model.')
term.Add('BodyGroupSet', 'Bodygroup set to "#".')
