term.Add('DataNotLoaded', 'YOUR DATA IS NOT LOADED. PLEASE WAIT. IF THIS POPS UP AGAIN, PLEASE POST A BUG REPORT!')
term.Add('UnknownError', 'An unknown error has occurred.')

term.Add('+Money', '+$#')
term.Add('-Money', '-$#')
term.Add('InvalidArg', 'Invalid argument.')
term.Add('CantFindPlayer', 'Couldn\'t find player #.')
term.Add('CannotAfford', 'You cannot afford this!')
term.Add('Bankrupt', 'You have gone bankrupt! All of your doors have been repossesssed.')
term.Add('TargetCannotAfford', '# cannot afford this!')
term.Add('NeedVIP', 'You need VIP this! Type /upgrades to get it.')
term.Add('NeedToWait', 'You need to wait # seconds to do this!')
term.Add('ChangeJob', '# has become # #.')
term.Add('CannotChangeJob', 'You cannot change jobs while #!')
term.Add('ChangeName', '# has changed their name to #')
term.Add('ChangeNameReserved', 'Name changed! Your old name is reserved for 24h, after that anyone may take it.')
term.Add('Welfare', 'Welfare time! You have received $# and lost # karma.')
term.Add('WelfareTaxed', 'Welfare time! You have received $#, paid $# in property tax, and lost # karma.')
term.Add('WelfareMissed', 'You received no welfare because you are arrested!')
term.Add('PropertyTax', 'You paid # in property taxes and gained # karma.')
term.Add('NotAllowedInSpawn', '# is not allowed in spawn!')
term.Add('GainedKarmaDrop', 'You\'ve earned # karma for playing. You\'ll earn # more in 15 minutes.')
term.Add('LostKarma', 'You have lost # karma for #!')
term.Add('LostKarmaNR', 'You have lost # karma.')
term.Add('LostKarmaDrugs', 'You have lost # karma for doing drugs.')
term.Add('EarnedKarmaHealing', 'You\'ve earned 5 karma for being an effective medic.')
term.Add('DrugOverdose', 'Your family will not mourn the death of a filthy junky like you.')
term.Add('DrugAids', 'You\'ve contracted aids due to your drug use')
term.Add('SpawnPropsSoFast', 'Please do not spawn props so fast.')
term.Add('RPNameShort', 'RP names must be longer than # characters.')
term.Add('RPNameLong', 'RP names must be shorter than # characters.')
term.Add('CannotRPName', 'You cannot change your RP name.')
term.Add('RPNameUnallowed', 'That name has unallowed characters (#).')
term.Add('SteamRPNameTaken', 'Your Steam name is already being used as someone\'s RP name, so we put a "1" after your name.')
term.Add('RPNameTaken', 'That RP name is already taken')
term.Add('EscapeDemotion', 'You tried to escape demotion. You failed, and have been demoted.')
term.Add('PlayerDemotedBy', '# has been demoted by # for #')
term.Add('PlayerDemoted', '# has been demoted.')
term.Add('PlayerNotDemoted', '# has not been demoted.')
term.Add('DemotionStarted', '# has started a demotion vote for #.')
term.Add('DemoteCooldown', 'You must wait # more seconds before starting another demotion vote.')
term.Add('YouDemotedX', 'You have demoted #.')
term.Add('DemotionReason', 'Please give a reason to demote.')
term.Add('DemoteReasonLong', 'Your demote reason must be below # characters.')
term.Add('DemoteSelf', 'You cannot demote yourself.')
term.Add('DemoteYouStarted', '# started a demotion vote on you for: #')
term.Add('UnableToDemote', 'You cannot call a demote on this team.')
term.Add('ChannelLimit', 'Choose a channel between 0 and 100.')
term.Add('ChannelSet', 'Channel set to #.')
term.Add('ChannelNotSet', 'You have not set your channe!')
term.Add('GiveMoneyLimit', 'Cannot give less than $1 away.')
term.Add('DropMoneyLimit', 'Cannot drop less than $1.')
term.Add('ChequeArg1', 'Invalid argument #1: recipient.')
term.Add('ChequeArg2', 'Invalid argument #2: amount.')
term.Add('PlayerGaveCash', '# has given you #.')
term.Add('PlayerSentWire', 'You wired # # after tax.')
term.Add('PlayerGotWire', '# has wired you #.')
term.Add('YouGaveCash', 'You gave # #.')
term.Add('MustLookAtPlayer', 'You must be looking at a player.')
term.Add('CantWhileRestrained', 'You cannot do that while restrained.')
term.Add('ClassNoWeaponKnowledge', 'Your class lacks the knowledge to use this weapon.')
term.Add('CantDropCarrierNoRoom', 'There is no room to drop your hostage here.')
term.Add('CantEscapeCarrierNoRoom', 'There\'s no room to escape! Keep struggling to injure your captor!')
term.Add('CantZiptieDistance', 'Your target is too far away now.')
term.Add('CutZiptieWithKnife', 'You must use a knife to cut zipties!')
term.Add('UpgradedSkill', 'Upgraded # to level #.')
term.Add('BoughtKarma', 'Bought # Karma for #')

term.Add('CannotMaterialThisWeapon', 'You cannot set the material of this weapon!')
term.Add('SetWepMaterial', 'Weapon material set!')

term.Add('HoesProfit', 'You have received $100 from your hoes.')
term.Add('CannotAffordHoe', '# cannot afford your services!')
term.Add('YouCannotAffordHoe', 'You cannot afford #\'s services!')
term.Add('GetCloser', 'You need to be closer to your target!')
term.Add('YouAreDead', 'You are dead!')
term.Add('NotAHoe', 'You are not a hoe.')
term.Add('NPCsDontFuck', 'You cannot fuck an NPC.')
term.Add('TargetFrozen', 'Your target is frozen.')
term.Add('WaitingForAnswer', 'Waiting for an answer.')
term.Add('TargetWontFuck', 'Your target does not wish to fuck.')
term.Add('TargetTooFar', 'Your target is too far away.')
term.Add('HoeTooFar', 'Your hoe is too far away.')
term.Add('+FuckCostPimp', '+ $# - 100 (Pimp\'s cut)')

term.Add('Warranted', '#\nПричина: #\nЗапрошено: #.')
term.Add('Wanted', '#\nПричина: #\nЗапрошено: #.')
term.Add('UnWanted', '#\nЗапрошено: #.')
term.Add('CannotUnwant', 'You cannot unwant this player since you did not want them!')
term.Add('Arrested', '# has been arrested.')
term.Add('UnArrested', '# has been released from jail.')
term.Add('YouWanted', 'You have wanted #')
term.Add('YouUnwanted', 'You unwanted #')

term.Add('DoorLocked', 'Locked!')
term.Add('DoorUnlocked', 'Unlocked!')
term.Add('TeamCannotOwnProperty', 'This team cannot own property.')
term.Add('PlayerTeamCannotOwnProperty', '# cannot own property.')
term.Add('PlayerPropertyAlreadyOwned', '# already owns a property.')

term.Add('PropertyAlreadyOwned', 'You already own a property! Sell it before you buy another.')
term.Add('PropertyBought', 'You bought the # property for # and gained # karma.')
term.Add('PropertySold', 'You sold the # property for #.')
term.Add('PropertySetTitle', 'Вы изменили имя собственности на #')
term.Add('PropertyNoneLeft', 'You have no properties to sell!')
term.Add('PropertyCoOwnerVotePending', '# is already pending an invite to co-own this property!')
term.Add('PropertyCoOwnerAdded', '# has been invited to co-own the # property.')
term.Add('PropertyCoOwnerAddedYou', '# has invited you to co-own the # property.')
term.Add('PropertyCoOwnerRemoved', '# has been removed from the # property.')
term.Add('PropertyCoOwnerRemovedYou', '# has removed you from the # property.')
term.Add('PropertOrDEnabled', 'Org access for # enabled.')
term.Add('PropertOrgDisabled', 'Org access for # disabled.')

term.Add('HotelTennantNotInRange', '# is too far away!')
term.Add('HotelTennantAdded', 'Added # to #')
term.Add('HotelTennantAddedYou', 'You have rented #.')
term.Add('HotelTennantDeclined', '# has declined to rent #.')
term.Add('HotelTennantAdded', 'Added # to #.')
term.Add('HotelTennantEvicted', 'You have evicted # from #.')
term.Add('HotelTennantEvictedYou', 'You have been evicted from #.')
term.Add('HotelTenantBankrupt', '# is bankrupt and can no longer afford your hotel room!')
term.Add('HotelPay', '# has paid # for their hotel room.')

term.Add('EventEnded', '# event has ended.')

-- Orgs
term.Add('OrgDisbanded', '# has been disbanded!')
term.Add('OrgPlayerKicked', '# has been kicked from #.')
term.Add('OrgPlayerYoureKicked', 'You have been kicked from #.')
term.Add('OrgMustLeaveFirst', 'You need to leave your current organization to create a new one.')
term.Add('OrgNameShort', 'Please make your organization name longer than 2 characters.')
term.Add('OrgNameLong', 'Please make your organization name shorter than 20 characters.')
term.Add('OrgNameTaken', 'This name is already taken. Please choose another!')
term.Add('OrgCannotAfford', 'You cannot afford to create an organization.')
term.Add('OrgCreated', 'You have successfully created your organization.')
term.Add('OrgMOTDChanged', '#\'s MoTD has been updated.')
term.Add('OrgColorChanged', 'You\'ve changed your organization color.')
term.Add('OrgPlayerQuit', '# has quit #!')
term.Add('OrgMemberLimit', 'You\'ve reached the limit of # org members!')
term.Add('OrgMemberJoined', '# has joined #.')
term.Add('OrgBankBusy', 'Somebody else is currently using the org bank. Wait a moment!')
term.Add('OrgBankFull', 'The org bank cannot exceed #!')
term.Add('OrgBankCannotAfford', 'The org bank contains insufficient funds for that.')
term.Add('OrgBankDeposited', 'You\'ve deposited # into the org bank (# has been taxed)')
term.Add('OrgBankInsufficient', 'The org bank cannot afford to withdraw that much!')
term.Add('OrgBankWithdrawn', 'You\'ve withdrawn # from the org bank.')
term.Add('OrgOwnershipTransferred', 'You\'ve transferred ownership of # to #.')
term.Add('OrgOwnershipTransferredYou', '# has transferred ownership of # to you.')
term.Add('OrgRenameFailed', 'Rename failed for some reason. Maybe that name was taken?')
term.Add('OrgRenamed', '# has been renamed to #.')
term.Add('OrgDisbandedBankReturned', '#\'s bank balance of $# has been returned to you.')
term.Add('OrgRankNameLength', 'Your rank must have a name.')
term.Add('OrgRankNameTaken', 'This rank name is already in use.')
term.Add('OrgTooManyInvites', 'This player has too many pending invites.')
term.Add('OrgInvitedAlready', 'This player already has a pending invitation to #.')

term.Add('MustBeNearbyMayorMachine', 'You must be in front of the computer in your office!')
term.Add('MustBeMayorSetLaws', 'You must be the mayor to set laws!')
term.Add('MustBeMayorResetLaws', 'You must be the mayor to reset laws!')
term.Add('LawsTooLong', 'Your laws are too long!')
term.Add('AgendaTooLong', 'Your agenda is too long!')
term.Add('LotteryTax', 'You have received # in lottery taxes.')
term.Add('LotteryWinner', '# has won # in the lottery!')
term.Add('NoLottery', 'Nobody else entered the lottery, so your money was returned.')
term.Add('NoLotteryTax', 'You have received $0 in lottery taxes because nobody entered.')
term.Add('NotInLottery', 'You did not enter the lottery.')
term.Add('InLottery', 'You entered the lottery for #.')
term.Add('NoLotteryAll', 'Nobody entered the lottery.')
term.Add('CannotLottery', 'You\'re unable to start a lottery right now.')
term.Add('LottoCost', 'Please specify an entry cost ($#-$#).')
term.Add('LotteryStarted', 'A lottery has started!')

term.Add('LockdownStarted', 'The mayor has initiated a lockdown. Please return to your homes!')
term.Add('CannotUnlockdown', 'You cannot end a lockdown right now.')
term.Add('LockdownEnded', 'The lockdown has ended.')
term.Add('LawsChanged', 'The laws have changed!')

term.Add('WarrantExpired', 'Your warrant has expired.')
term.Add('PlayerIsPoliceWant', 'You cannot want #. Demote them for corruption.')
term.Add('PlayerIsPoliceWarrant', 'You cannot warrant #. Demote them for corruption.')
term.Add('PlayerCannotBeWanted', '# cannot be wanted!')
term.Add('PlayerAlreadyWanted', '# is already wanted!')
term.Add('PlayerAlreadyWarranted', '# is already warranted!')
term.Add('PlayerNotWanted', '# is not wanted!')
term.Add('PlayerNotWarranted', '# is not warranted!')
term.Add('MustTargetPlayerWithWarrant', 'You need a warrant to break into a players base!')
term.Add('WarrantRequestAcc', 'Your warrant request was accepted.')
term.Add('WantReasonTooLong', 'Want reason is too long! 40 characters max!')

term.Add('HitComplete', 'Hit on # complete.')
term.Add('HitKindaFailed', 'There was some sort of miscommunication that has caused you to place a hit on yourself.')
term.Add('YourHitComplete', 'You have been killed by a hitman.')
term.Add('CantHitYourself', 'You cannot put a hit on yourself!')
term.Add('CantPlaceHit', 'Hitmen cannot place hits!')
term.Add('CantPlaceHitGrace', 'You cannot place a hit on the mayor during mayor grace!')
term.Add('HitPriceLimit', 'Hit prices must be between # and #.')
term.Add('HitTimer', 'You cannot place another hit for # seconds.')
term.Add('MultiHit', 'You cannot place a hit on the same person twice in a row!')
term.Add('HitCooldown', 'This player died to a hit too recently.')
term.Add('BountyIncrease', 'You increased the bounty on # by #.')
term.Add('HitPlaced', 'You have placed a hit on # for #.')
term.Add('HitmanFailed', 'You have failed as a hitman!')
term.Add('HitmanKilledAll', 'It\'s your lucky day! That hitman was carrying the # bounty that was on your head.')
term.Add('Need911Reason', 'Please input a reason for your 911 call!')
term.Add('Canceled911', 'You\'ve canceled your 911 call.')

term.Add('EmployeeChangedJob', 'Your employee has changed jobs!')
term.Add('EmployeeChangedJobYou', 'Your employer\'s contract has been terminated because you changed jobs!')
term.Add('EmployeeLeft', 'Your employee has disconnected!')
term.Add('EmployerLeft', 'Your employer has disconnected!')
term.Add('PlayerNotHirable', '# is not hirable.')
term.Add('EmployeeTriedEmploying', 'You are seeking work currently. You cannot hire an employee!')
term.Add('AlreadyEmployed', 'You\'re already employed!')
term.Add('CannotAffordEmployee', 'You cannot affort to hire anyone!')
term.Add('EmployRequestSent', '# has been sent your request for hire.')
term.Add('SetHirePriceToHigh', 'You can\'t set your hire price higher than #!')
term.Add('SetHirePrice', 'You have set your hire price to #.')
term.Add('YouHired', 'You have hired # for #.')
term.Add('YouAreHired', '# has hired you for #.')
term.Add('EmployRequestDen', '# has denied your request for hire.')
term.Add('EmployeeFired', 'You have fired #.')
term.Add('EmployeeFiredYou', '# has fired you!')
term.Add('EmployeeQuit', '# has quit their job with you!')
term.Add('EmployeeQuitYou', 'You have quit for job for #.')

term.Add('CannotTool', 'Your rank cannot use the "#" tool!')
term.Add('DupeRestrictedEnts', 'You cannot spawn dupes containing these entities!')
term.Add('DupeNeedsRepair', 'Your dupe has blacklisted models are entities in and will likely be broken. Click again within 5 seconds to paste it anyway.')
term.Add('DupeRemovedModel', '# blacklisted props and # constraints have been removed from your dupe.')
term.Add('WhitelistFull', 'The whitelist is full #/750')
term.Add('CacheFull', 'The model precache is full #/100!')
term.Add('PropWhitelisted', '# has been whitelisted by #.')
term.Add('PropBlacklisted', '# has been blacklisted by #.')
term.Add('UnsharedPropsYou', 'You have unshared your props with #.')
term.Add('UnsharedProps', '# has unshared their props with you.')
term.Add('OrgSharedProps', '# has shared their props with the org.')
term.Add('OrgUnsharedProps', '# has unshared their props with the org.')
term.Add('SharedPropsYou', 'You have shared your props with #.')
term.Add('SharedProps', '# has shared their props with you.')
term.Add('PPGroupSet', '# has been set to group # by #.')
term.Add('PropNotWhitelisted', '# is not whitelisted!')

term.Add('CannotDestroyWeapon', 'You cannot destroy this weapon!')

term.Add('YourEntDestroyed', 'Your # was destroyed!')
term.Add('InvalidURL', 'Invalid URL!')
term.Add('VideoFailed', 'Failed to load video: #.')
term.Add('VideoTooLong', 'You cannot play videos over # minutes!')
term.Add('FoodLimitReached', 'You have reached the food limit!')
term.Add('BoughtFoodProduction', 'You have paid # for food production.')
term.Add('SoldFoodNoProf', 'You sold some food and made no profit.')
term.Add('SoldFood', 'You sold some food and made # profit.')
term.Add('BoughtFood', 'You have purchased food for #.')
term.Add('MicrowaveFoodType', 'Microwave set to #')
term.Add('ThereIsACook', 'There is a cook. You can\'t do this!')
term.Add('EmptyShipment', 'There is nothing in the shipment.')

term.Add('GCMessageLimit', 'Your message needs to be more than 1 character!')

term.Add('CantSuicideJail', 'You can\'t suicide in jail.')
term.Add('CantSuicideWanted', 'You can\'t suicide while wanted.')
term.Add('CantSuicideFrozen', 'You can\'t suicide while frozen.')
term.Add('CantSuicideLiveFor', 'You have too much to live for!')
term.Add('CantSuicideRestrained', 'You can\'t suicide while restrained.')
term.Add('YouSuicided', 'You have lost 5 karma for being a disgrace to your family.')

term.Add('CantPurchaseUpgrade', 'You cannot purchase this. #')

term.Add('RPItemBought', 'You bought # for #.')
term.Add('RPItemBoughtLimit', 'You bought #/# # for #.')

term.Add('CantAdminCleanup', 'You cannot use admin cleanup!')

term.Add('MayorHasDied', 'The mayor has died!')
term.Add('YouWereBailed', '# has bailed you from jail!')

term.Add('AmmoLabProfit', 'You received $# from your ammo lab.')
term.Add('BoughtAmmo', 'You have bought ammo for $#.')
term.Add('AmmoLabExploded', 'Your ammo lab has exploded!')

term.Add('ArmorLabProfit', 'You received $# from your armor lab.')
term.Add('BoughtArmor', 'You have bought armor for $#.')
term.Add('ArmorLabExploded', 'Your armor lab has exploded!')

term.Add('ChequeFound', 'You have found # in a cheque made out to you from #.')
term.Add('ChequeMadeTo', 'This cheque is made out to #.')
term.Add('ChequeTorn', 'You have torn up the cheque.')
term.Add('MoneyFound', 'You have found $#!')

term.Add('MustBeHobo', 'You need to be a hobo to use this!')
term.Add('AlreadyDisguised', 'You\'re already disguised!')
term.Add('GunLicenseActive', 'You have activated your gun license.')
term.Add('AlreadyHasGunLicense', 'You already have a gun license!')
term.Add('YouGotAIDS', 'You have contracted AIDS and will soon die.')
term.Add('YouGotHIV', 'You have contracted HIV from an exposed needle.')
term.Add('STDCured', 'You have cured your sexually tramsitted diseases.')
term.Add('PimpSTDCured', 'You have cured # of their sexually tramsitted diseases.')
term.Add('NowDisguised', 'You are now disguised as a #.')
term.Add('DisguiseWorn', 'Your disguise has worn off.')
term.Add('DisguiseLimit', 'You cannot disguise again for # minutes.')

term.Add('MedLabProfit', 'You received $# from your medic lab.')
term.Add('BoughtHealth', 'You have bought health for $#.')
term.Add('MedLabExploded', 'Your medic lab has exploded!')

term.Add('KeypadControlsX', 'This keypad controls # entities.')
term.Add('EntityControlledByX', 'This entity is controlled by # keypads.')

term.Add('VoteAlone', 'You have won the vote since you are alone in the server.')
term.Add('BannedFromJob', 'You are restricted from that job for #s. Reason: #.')
term.Add('BannedFromJobPerma', 'You are restricted from that job. Reason: #.')
term.Add('CantGoPolice', 'You were recently killed. You need to wait # seconds to go police.')
term.Add('VotedTooSoon', 'Please wait # more seconds before voting to become this job.')
term.Add('AlreadyThisJob', 'You\'re already this job!')
term.Add('JobLimit', 'Team limit has already been reached.')
term.Add('RegisteredForVote', 'You have registered for the upcoming vote!')
term.Add('AlreadyVoting', 'Voting has already begun. You\'re too late!')
term.Add('AdminRoomNotSet', 'The sit room location has not been set!')
term.Add('JobNeedsPlaytime', 'You need # hours play time or vip for this job!')
term.Add('JobNeedsAdmin', 'You must be moderator+ for this job.')
term.Add('JobNeedsSA', 'You must be SA+ for this job.')
term.Add('JobNeedsBanned', 'You need to be banned from the server to become this class.')
term.Add('JobNeedsManualSet', 'You need to be set to this job by an admin.')
term.Add('IncorrectJob', 'You are not currently the correct job to do that!')
term.Add('VoteStarted', 'Vote has been created.')
term.Add('CannotJob', 'You cannot change your job right now.')
term.Add('JobLenShort', 'Jobs must be more than # characters.')
term.Add('JobLenLong', 'Jobs must be less than # characters.')

term.Add('CannotPurchaseItem', 'You\'re not allowed to purchase this item.')
term.Add('ItemUnavailable', 'That item is unavailable.')
term.Add('UnableToItem', 'You were unable to purchase that item.')
term.Add('ShipmentCooldown', 'Please wait before spawning another shipment.')

term.Add('MedicExists', 'You cannot buy health because there are medics.')
term.Add('HealthIsFull', 'Your health is full already!')

term.Add('CannotDropWeapon', 'You cannot drop this weapon!')
term.Add('LookAtEntity', 'You need to be looking at an entity!')
term.Add('CannotSetPrice', 'You cannot set the price of this entity!')

term.Add('AnalProlapse', 'You have overexerted your anus and died from anal prolapse.')
term.Add('NoMorePoo', 'You have no more poo left!')
term.Add('NotARapist', 'You are not a rapist.')
term.Add('RapeSOD', 'You cannot rape Staff on Duty.')
term.Add('RapeFailed', 'Rape attempt failed!')
term.Add('RapeAttempted', 'Someone has attempted to intrude your butthole.')
term.Add('Raped', 'You have intruded #\'s butthole.')
term.Add('YouAreRaped', 'Someone has intruded your butthole.')
term.Add('AnalProlapseShort', 'You have died from anal prolapse.')
term.Add('DickFellOff', 'Your dick has fallen off.')
term.Add('NoRangeOfMotion', 'You lack the range of motion to rape right now.')
term.Add('RapeStruggled', 'You struggled free from rape!')
term.Add('RapeVictimStruggled', 'Your victim struggled free!')

term.Add('CannotVote', 'You cannot vote.')
term.Add('FoundNothing', 'You found nothing.')
term.Add('RobberyAttempt', 'You felt a slight movement in your pocket.')
term.Add('YouRobbed', 'You have stolen $#!')
term.Add('YouAreRobbed', 'Your wallet feels lighter.')
term.Add('YouRobbedItem', 'You pulled out an item. Grab it fast!')
term.Add('YouAreRobbedItem', 'Your pocket feels lighter.')

term.Add('NoteUpdated', 'Note text updated.')
term.Add('USENote', 'Press USE on your note to edit the text.')

term.Add('OrgYouAreStuck', 'You\'re stuck! >:)')
term.Add('OrgYourRank', '# has set your rank to \'#\'.')
term.Add('OrgSetRank', '# has been set to \'#\'.')
term.Add('OrgUnknownRank', 'Unknown rank \'#\'.')
term.Add('OrgRankRename', 'Rank \'#\' renamed to \'#\'.')
term.Add('OrgReorderLimit', 'You cannot reorder the highest and lowest ranks.')
term.Add('OrgRankUpdated', 'Rank \'#\' updated.')
term.Add('OrgMaxRanks', 'Maximum ranks reached.')
term.Add('OrgRankCreated', 'Rank \'#\' created.')
term.Add('OrgDeleteLimit', 'You cannot delete the top and bottom ranks.')
term.Add('OrgRankDelete', 'Rank \'#\' removed.')
term.Add('OrgBannerUpdated', 'Banner updated.')
term.Add('OrgPlayerInvited', 'You invited # for $#.')

term.Add('SetOutfit', 'Your outfit has been set to #')

-- Stools
term.Add('CantMetagameKeypad', 'You must use a keypad for your fading door!')
term.Add('FadeDoorCreated', 'Fading door created.')
term.Add('FadeDoorCreatedExtra', 'Fading door created. Now, right click again to place a keypad.')
term.Add('InvalidPassword', 'Invalid password!')
term.Add('KeypadHoldLength', 'The hold length must be at least # seconds.')
term.Add('NoCollidedWorld', 'World collisions disabled.')
term.Add('CollidedWorld', 'World collisions enabled.')
term.Add('NoCollided', 'Collsions disabled.')
term.Add('Collided', 'Collsions enabled.')
term.Add('UnBreakable', 'Unbreakable enabled.')
term.Add('Breakable', 'Unbreakable disabled.')
term.Add('ColorizedYou', 'Colorized yourself.')
term.Add('DecolorizedYou', 'Decolorized yourself')
term.Add('ColorizedPlayer', 'Colorized #.')
term.Add('DecolorizedPlayer', 'Decolorized #.')
term.Add('DecolorizedAll', 'Decolorized all players.')
term.Add('FadingDoorAdded', 'Linked prop to fading door.')
term.Add('FadingDoorRemoved', 'Unlinked prop from fading door.')
term.Add('FadingDoorOnlyProps', 'Only props can be made into fading doors!')
term.Add('FadingDoorMaxProps', 'You\'re only allowed to make # props into one fading door!')
term.Add('FadingDoorNoProps', 'Right click a prop to link it before you make a pad!')

-- Sandbox
term.Add('SboxXLimit', 'You\'ve hit the limit of # #!')
term.Add('SboxSpawned', 'Spawned #/# #.')

-- Entities folder
term.Add('ImageNSFW', 'This image has been detected as inappropriate. Please use another.')

term.Add('PlayerTaserResistance', '# has built up a tolerance and was unaffected by the taser this time!')
term.Add('PlayerTaserResistanceSelf', 'You were tased, but have built up a tolerance and were unaffected this time!')

term.Add('ArcadeMachineUse', 'Get ready to play!')
term.Add('PlayerNotInJail', '# is not in jail.')
term.Add('PlayerFuckedBailing', 'You dumbass, the cops are hot on your tail now!')
term.Add('PlayerBailedPlayer', 'You have bailed # for # and gained # karma.')
term.Add('PlayerTookDonationBox', 'You have taken #.')
term.Add('YouDontOwnThis', 'You do not own this!')
term.Add('PlayerReceivedDonationBox', 'Someone has placed # in your donation box.')
term.Add('PlayerNotWanted', 'This player is not wanted!')
term.Add('PlayerTookMoneyBasket', 'You have taken #.')
term.Add('PrinterIsFull', 'This printer\'s ink is already full!')
term.Add('PrinterRefilled', 'You\'ve refilled this printer for #.')
term.Add('PlayerSoldDrugs', 'You\'ve sold your # for #.')

term.Add('SoldItem', 'You sold a item and made # profit and gained # karma.')
term.Add('BoughtItem', 'You have purchased a item for #.')

term.Add('GamblingMachinePlayerCannotAfford', 'You cannot afford to play this # machine!')
term.Add('GamblingMachineHouseCannotAfford', 'You cannot afford your # machine! It is now out of service.')
term.Add('GamblingMachineOwnerCannotAfford', 'The owner of this # machine can no longer afford to operate. It is now out of service.')
term.Add('GamblingMachineInService', 'Your # machine is now in service.')
term.Add('GamblingMachineIOutService', 'Your # machine is now out of service.')

term.Add('5050PlayerWin', 'You won # playing FiftyFifty!')
term.Add('5050PlayerLose', 'You lost # playing FiftyFifty!')
term.Add('5050Tie', 'You tied and got your money back.')

term.Add('BasicSlotsPlayerWin', 'You won # playing Basic Slots!')
term.Add('BasicSlotsPlayerLose', 'You lost # playing Basic Slots!')

term.Add('SpinWheelPlayerWin', 'You won # playing Spin Wheel!')
term.Add('SpinWheelPlayerLose', 'You lost # playing Spin Wheel!')

term.Add('AlreadyHaveWeapon', 'You already have this weapon equipped! Use your pocket.')

term.Add('BiometricAddedAccess', 'Added # to scanner')
term.Add('BiometricRemovedAccess', 'Removed # from scanner')
term.Add('BiometricToggledOrgOwn', 'Toggled org ownership')
term.Add('BiometricCopiedSettings', 'Copied settings to # scanners')

term.Add('TollMadeProfit', 'You made # (# has been taxed) from your toll.')

term.Add('YourItemLabRanOut', 'Your item lab has ran out!')

-- Weapons folder
term.Add('ArrestBatonBonus', 'You have received a # bonus and # karma for destroying this illegal entity.')
term.Add('ArrestBatonArrested', 'You\'ve been arrested by #.')
term.Add('ArrestBatonYouArrested', 'You arrested #.')
term.Add('PlayerRangDoorbell', 'Someone has rang your doorbell.')
term.Add('KeysCooldown', 'The lock on this door is busted! Try again in # seconds!')
term.Add('UnarrestBatonTarg', 'You\'ve been unarrested by #.')
term.Add('UnarrestBatonOwn', 'You unarrested #.')

term.Add('ApparelPurchased', 'You have purchased # for #.')
term.Add('ApparelEquiped', '# equipped!')
term.Add('ApparelRemoved', '# removed!')

term.Add('BURGHungerImmune', 'You\'re immune to hunger until you die, now!')
term.Add('BURGNotPeople', 'Silly burger, burgers aren\'t people!')

term.Add('CannotPocket', 'You cannot put # in your pocket!')
term.Add('CannotPocketCooldown', 'You need to wait # seconds before you can pocket this!')
term.Add('CannotPocketUsedShipments', 'Merchant classes cannot pocket partially full shipments!')

-- Kombat
term.Add('KombatFull', 'Sorry, all # slots for Kombat have been filled already.')
term.Add('KombatMissedDeadline', 'Sorry, you\'ve missed the deadline to sign up for Kombat.')
term.Add('KombatRestrained', 'Sorry, you cannot enter Kombat while restrained.')
term.Add('KombatCarrying', 'Sorry, you cannot enter Kombat while carrying someone.')

-- Gun Lab
term.Add('ItemLabRefilled', 'You\'ve filled this Lab for $#. It now has # metal.')
term.Add('ItemLabCrafting', 'Used # metal to begin crafting #.')

-- Bodygroups
term.Add('ModelNoBodyGroups', 'This model does not contain any preset bodygroups.')
term.Add('BodyGroupPermission', 'You do not have permission to set bodygroups on this model/player.')
term.Add('BodyGroupNotFound', 'The bodygroup "#" was not found for this model.')
term.Add('BodyGroupSet', 'Bodygroup set to "#".')

-- bitminers
term.Add('MinersOverheating', 'Ваш битмайнер перегревается!')
term.Add('MinersPowered', 'Вы включили битмайнеры!')
term.Add('MinersNoPowerSource', 'У вашего битмайнера отсутсвует питание.')
term.Add('MinersShutdown', 'Вы выключили битмайнеры!')
term.Add('MinersWithdraw', '# было снято с битмайнера!')
term.Add('MinersNoExchange', 'У вас нету биткойнов для обмена!')
term.Add('MinersNeedRGB', 'Эта функция не работает без RGB модуля!')
term.Add('MinersMaxAmount', 'Вы достигли лимита по установленным майнерам.')
term.Add('MinersMoreUPS', 'Установите ещё один UPS для добавления новых майнеров.')
term.Add('MinersMaxUPS', 'Вы достигли лимита по установке UPS на этот битмайнер!')
term.Add('MinersMaxVent', 'Вы достигли максимального уровня по установке охлаждения на этот битмайнер!')
term.Add('MinersBestVent', 'На вашем майнере уже установлено более лучшее охлаждение!')
term.Add('MinersRGBInstalled', 'RGB подсветка успешно установлена!')
term.Add('MinersBestRGB', 'На вашем битмайнере уже установлена RGB подсветка!')
term.Add('MinersExplodedFire', 'От полученного урона ваш битмайнер загорелся и взорвался!')
term.Add('MinersExploded', 'От полученного урона ваш битмайнер взорвался!')
term.Add('MinersPowerConnected', 'У битмайнера уже имеется источник питания!')
term.Add('MinersPowerAttach', 'Пожалуйста подключите кабель к источнику питания!')
term.Add('MinersPowerToShelf', 'Пожалуйста подключите тройник к битмайнеру!')
term.Add('MinersGeneratorOn', 'Вы включили генератор!')
term.Add('MinersGeneratorFuel', 'В генераторе отсутсвует топливо!')
term.Add('MinersGeneratorAlreadyOn', 'Генератор уже включён!')
term.Add('MinersGeneratorOff', 'Генератор был выключен!')
term.Add('MinersGeneratorAlreadyOff', 'Генератор уже выключен!')
term.Add('MinersGeneratorOutFuel', 'В вашем генераторе кончилось топливо!')
term.Add('MinersGeneratorFullFuel', 'Топливный бак генератора полон!')
