term.Add('DataNotLoaded', 'ВАШИ ДАННЫЕ НЕ ЗАГРУЖЕНЫ. ПОЖАЛУЙСТА, ПОДОЖДИТЕ. ЕСЛИ ЭТО СЛУЧИТСЯ СНОВА, ПОЖАЛУЙСТА, СООБЩИТЕ НАМ ОБ ЭТОМ!')
term.Add('UnknownError', 'Произошла неизвестная ошибка.')

term.Add('+Money', '+$#')
term.Add('-Money', '-$#')
term.Add('InvalidArg', 'Недействительный аргумент.')
term.Add('CantFindPlayer', 'Невозможно найти игрока #.')
term.Add('CannotAfford', 'Вы не можете себе это позволить!')
term.Add('Bankrupt', 'Вы обанкротились! Вся ваша собственность была распродана.')
term.Add('TargetCannotAfford', '# не может себе это позволить!')
term.Add('NeedVIP', 'Вам нужен VIP статус! Напишите /upgrades чтобы купить.')
term.Add('NeedToWait', 'Вам нужно подождать # секунд чтобы сделать это!')
term.Add('ChangeJob', '# теперь # #.')
term.Add('CannotChangeJob', 'Вы не можете сменить работу в течении #!')
term.Add('ChangeName', '# изменил имя на #')
term.Add('ChangeNameReserved', 'Name changed! Your old name is reserved for 24h, after that anyone may take it.')
term.Add('Welfare', 'Социальная выплата! Вы получили $# и потеряли # кармы.')
term.Add('WelfareTaxed', 'Социальная выплата! Вы получили $#, и заплатили $# за налог на собственность, а так же потеряли # кармы.')
term.Add('WelfareMissed', 'Вы не получили социальную выплату из-за нахождения под арестом!')
term.Add('PropertyTax', 'Вы заплатили # за налог на собственность и получили # кармы.')
term.Add('NotAllowedInSpawn', '# недопустимо на спавне!')
term.Add('GainedKarmaDrop', 'Вы получили # кармы за игру на сервере. Вы получите ещё # через 15 минут.')
term.Add('LostKarma', 'Вы потеряли # кармы за #!')
term.Add('LostKarmaNR', 'Вы потеряли # кармы.')
term.Add('LostKarmaDrugs', 'Вы потеряли # кармы за использование наркотиков.')
term.Add('EarnedKarmaHealing', 'Вы получили 5 кармы за хорошую работу медиком.')
term.Add('DrugOverdose', 'Your family will not mourn the death of a filthy junky like you.')
term.Add('DrugAids', 'You\'ve contracted aids due to your drug use')
term.Add('SpawnPropsSoFast', 'Пожалуйста не спавните пропы так быстро.')
term.Add('RPNameShort', 'Имя должно быть длиннее # символов.')
term.Add('RPNameLong', 'Имя должно быть короче # символов.')
term.Add('CannotRPName', 'Вы не можете сменить ваше имя.')
term.Add('RPNameUnallowed', 'Ваше имя содержит запрещённые символы (#).')
term.Add('SteamRPNameTaken', 'Your Steam name is already being used as someone\'s RP name, so we put a "1" after your name.')
term.Add('RPNameTaken', 'Это имя уже занято')
term.Add('EscapeDemotion', 'You tried to escape demotion. You failed, and have been demoted.')
term.Add('PlayerDemotedBy', '# has been demoted by # for #')
term.Add('PlayerDemoted', '# has been demoted.')
term.Add('PlayerNotDemoted', '# has not been demoted.')
term.Add('DemotionStarted', '# has started a demotion vote for #.')
term.Add('DemoteCooldown', 'You must wait # more seconds before starting another demotion vote.')
term.Add('YouDemotedX', 'You have demoted #.')
term.Add('DemotionReason', 'Please give a reason to demote.')
term.Add('DemoteReasonLong', 'Your demote reason must be below # characters.')
term.Add('DemoteSelf', 'You cannot demote yourself.')
term.Add('DemoteYouStarted', '# started a demotion vote on you for: #')
term.Add('UnableToDemote', 'You cannot call a demote on this team.')
term.Add('ChannelLimit', 'Выберите канал между 0 и 100.')
term.Add('ChannelSet', 'Канал изменён на #.')
term.Add('ChannelNotSet', 'Вы не настроили свой канал!')
term.Add('GiveMoneyLimit', 'Нельзя передать меньше чем $1.')
term.Add('DropMoneyLimit', 'Нельзя выбросить меньше чем $1.')
term.Add('ChequeArg1', 'Недействительный аргумент #1: получатель.')
term.Add('ChequeArg2', 'Недействительный аргумент #2: сумма.')
term.Add('PlayerGaveCash', '# передал вам #.')
term.Add('PlayerSentWire', 'Вы перечислили # # с учётом налогов.')
term.Add('PlayerGotWire', '# перечислил вам #.')
term.Add('YouGaveCash', 'Вы передали # #.')
term.Add('MustLookAtPlayer', 'Вы должны смотреть на игрока.')
term.Add('CantWhileRestrained', 'Вы не можете сделать это пока вы связанны.')
term.Add('ClassNoWeaponKnowledge', 'Your class lacks the knowledge to use this weapon.')
term.Add('CantDropCarrierNoRoom', 'There is no room to drop your hostage here.')
term.Add('CantEscapeCarrierNoRoom', 'There\'s no room to escape! Keep struggling to injure your captor!')
term.Add('CantZiptieDistance', 'Your target is too far away now.')
term.Add('CutZiptieWithKnife', 'You must use a knife to cut zipties!')
term.Add('UpgradedSkill', 'Upgraded # to level #.')
term.Add('BoughtKarma', 'Приобретено # Кармы за #')

term.Add('CannotMaterialThisWeapon', 'Вы не можете изменить материал этого оружия!')
term.Add('SetWepMaterial', 'Материал оружия изменён!')

term.Add('HoesProfit', 'Вы получили $100 от ваших шлюх.')
term.Add('CannotAffordHoe', '# не может позволить себе ваши услуги!')
term.Add('YouCannotAffordHoe', 'You cannot afford #\'s services!')
term.Add('GetCloser', 'Вы должны быть ближе к вашей цели!')
term.Add('YouAreDead', 'Вы мертвы!')
term.Add('NotAHoe', 'Вы не шлюха.')
term.Add('NPCsDontFuck', 'Вы не можете переспать с NPC.')
term.Add('TargetFrozen', 'Ваша цель заморожена.')
term.Add('WaitingForAnswer', 'Waiting for an answer.')
term.Add('TargetWontFuck', 'Your target does not wish to fuck.')
term.Add('TargetTooFar', 'Your target is too far away.')
term.Add('HoeTooFar', 'Your hoe is too far away.')
term.Add('+FuckCostPimp', '+ $# - 100 (Pimp\'s cut)')

term.Add('Warranted', '#\nПричина: #\nЗапрошено: #.')
term.Add('Wanted', '#\nПричина: #\nЗапрошено: #.')
term.Add('UnWanted', '#\nЗапрошено: #.')
term.Add('CannotUnwant', 'Вы не можете убрать из розыска неразыскиваемого игрока!')
term.Add('Arrested', '# был арестован.')
term.Add('UnArrested', '# был выпущен из тюрьмы.')
term.Add('YouWanted', 'Вы объявили в розыск #')
term.Add('YouUnwanted', 'Вы убрали из розыска #')

term.Add('DoorLocked', 'Закрыто!')
term.Add('DoorUnlocked', 'Открыто!')
term.Add('TeamCannotOwnProperty', 'Ваша профессия не может владеть собственностью.')
term.Add('PlayerTeamCannotOwnProperty', '# не может владеть собственностью.')
term.Add('PlayerPropertyAlreadyOwned', '# уже владеет собственностью.')

term.Add('PropertyAlreadyOwned', 'Вы уже владеете собственностью! Продайте её перед покупкой новой.')
term.Add('PropertyBought', 'Вы приобрели # за # и получили # кармы.')
term.Add('PropertySold', 'Вы продали # за #.')
term.Add('PropertySetTitle', 'Вы изменили имя собственности на #')
term.Add('PropertyNoneLeft', 'У вас нет собственности на продажу!')
term.Add('PropertyCoOwnerVotePending', '# уже имеет приглашение на совладение этой собственностью!')
term.Add('PropertyCoOwnerAdded', '# был приглашён стать совладельцем собственности #.')
term.Add('PropertyCoOwnerAddedYou', '# пригласил вас стать совладельцем собственности #.')
term.Add('PropertyCoOwnerRemoved', '# был удалён из собственности #.')
term.Add('PropertyCoOwnerRemovedYou', '# удалил вас из собственности #.')
term.Add('PropertOrDEnabled', 'Org access for # enabled.')
term.Add('PropertOrgDisabled', 'Org access for # disabled.')

term.Add('HotelTennantNotInRange', '# is too far away!')
term.Add('HotelTennantAdded', 'Added # to #')
term.Add('HotelTennantAddedYou', 'You have rented #.')
term.Add('HotelTennantDeclined', '# has declined to rent #.')
term.Add('HotelTennantAdded', 'Added # to #.')
term.Add('HotelTennantEvicted', 'You have evicted # from #.')
term.Add('HotelTennantEvictedYou', 'You have been evicted from #.')
term.Add('HotelTenantBankrupt', '# is bankrupt and can no longer afford your hotel room!')
term.Add('HotelPay', '# has paid # for their hotel room.')

term.Add('EventEnded', '# эвент закончился.')

-- Orgs
term.Add('OrgDisbanded', '# has been disbanded!')
term.Add('OrgPlayerKicked', '# has been kicked from #.')
term.Add('OrgPlayerYoureKicked', 'You have been kicked from #.')
term.Add('OrgMustLeaveFirst', 'You need to leave your current organization to create a new one.')
term.Add('OrgNameShort', 'Please make your organization name longer than 2 characters.')
term.Add('OrgNameLong', 'Please make your organization name shorter than 20 characters.')
term.Add('OrgNameTaken', 'This name is already taken. Please choose another!')
term.Add('OrgCannotAfford', 'You cannot afford to create an organization.')
term.Add('OrgCreated', 'You have successfully created your organization.')
term.Add('OrgMOTDChanged', '#\'s MoTD has been updated.')
term.Add('OrgColorChanged', 'You\'ve changed your organization color.')
term.Add('OrgPlayerQuit', '# has quit #!')
term.Add('OrgMemberLimit', 'You\'ve reached the limit of # org members!')
term.Add('OrgMemberJoined', '# has joined #.')
term.Add('OrgBankBusy', 'Somebody else is currently using the org bank. Wait a moment!')
term.Add('OrgBankFull', 'The org bank cannot exceed #!')
term.Add('OrgBankCannotAfford', 'The org bank contains insufficient funds for that.')
term.Add('OrgBankDeposited', 'You\'ve deposited # into the org bank (# has been taxed)')
term.Add('OrgBankInsufficient', 'The org bank cannot afford to withdraw that much!')
term.Add('OrgBankWithdrawn', 'You\'ve withdrawn # from the org bank.')
term.Add('OrgOwnershipTransferred', 'You\'ve transferred ownership of # to #.')
term.Add('OrgOwnershipTransferredYou', '# has transferred ownership of # to you.')
term.Add('OrgRenameFailed', 'Rename failed for some reason. Maybe that name was taken?')
term.Add('OrgRenamed', '# has been renamed to #.')
term.Add('OrgDisbandedBankReturned', '#\'s bank balance of $# has been returned to you.')
term.Add('OrgRankNameLength', 'Your rank must have a name.')
term.Add('OrgRankNameTaken', 'This rank name is already in use.')
term.Add('OrgTooManyInvites', 'This player has too many pending invites.')
term.Add('OrgInvitedAlready', 'This player already has a pending invitation to #.')

term.Add('MustBeNearbyMayorMachine', 'Вы должны быть перед компьютером в вашем офисе!')
term.Add('MustBeMayorSetLaws', 'Вы должны быть мэром для изменения законов!')
term.Add('MustBeMayorResetLaws', 'Вы должны быть мэром для обнуления законов!')
term.Add('LawsTooLong', 'Ваши законы слишком длинные!')
term.Add('AgendaTooLong', 'Ваша агенда слишком длинная!')
term.Add('LotteryTax', 'Вы получили # из налогов с лотереи.')
term.Add('LotteryWinner', '# выиграл # в лотерею!')
term.Add('NoLottery', 'Никто другой не принял участия в лотерее, ваши деньги были возвращены.')
term.Add('NoLotteryTax', 'Вы получили $0 из налогов с лотереи, так как никто не принял участия.')
term.Add('NotInLottery', 'Вы не приняли участия в лотерее.')
term.Add('InLottery', 'Вы учавствуете в лотерее на #.')
term.Add('NoLotteryAll', 'Никто другой не принял участия в лотерее.')
term.Add('CannotLottery', 'Вы не можете начать лотерею прямо сейчас.')
term.Add('LottoCost', 'Пожалуйста укажите стоимоть участия в лотерее ($#-$#).')
term.Add('LotteryStarted', 'Началась лотерея!')

term.Add('LockdownStarted', 'Мэр объявил начало комендатского часа. Пожалуйста вернитесь домой!')
term.Add('CannotUnlockdown', 'Вы не можете закончить комендантский час прямо сейчас.')
term.Add('LockdownEnded', 'Комендантский час закончился.')
term.Add('LawsChanged', 'Законы были изменены!')

term.Add('WarrantExpired', 'Ваш ордер на обыск истёк.')
term.Add('PlayerIsPoliceWant', 'Вы не можете объявить в розыск #. Увольте его за коррупцию.')
term.Add('PlayerIsPoliceWarrant', 'Вы не можете запросить ордер на обыск #. Увольте его за коррупцию.')
term.Add('PlayerCannotBeWanted', '# не может быть объявлен в розыск!')
term.Add('PlayerAlreadyWanted', '# уже в розыске!')
term.Add('PlayerAlreadyWarranted', 'У вас уже есть ордер на обыск #!')
term.Add('PlayerNotWanted', '# не разыскивается!')
term.Add('PlayerNotWarranted', 'У вас нет ордера на обыск #!')
term.Add('MustTargetPlayerWithWarrant', 'Вам нужен ордер на обыск чтобы проникнуть на базу!')
term.Add('WarrantRequestAcc', 'Ваш ордер на обыск истёк.')
term.Add('WantReasonTooLong', 'Причина розыска слишком длинная! Максимум 40 символов!')

term.Add('HitComplete', 'Заказ на # завершён.')
term.Add('HitKindaFailed', 'There was some sort of miscommunication that has caused you to place a hit on yourself.')
term.Add('YourHitComplete', 'You have been killed by a hitman.')
term.Add('CantHitYourself', 'You cannot put a hit on yourself!')
term.Add('CantPlaceHit', 'Hitmen cannot place hits!')
term.Add('CantPlaceHitGrace', 'You cannot place a hit on the mayor during mayor grace!')
term.Add('HitPriceLimit', 'Hit prices must be between # and #.')
term.Add('HitTimer', 'You cannot place another hit for # seconds.')
term.Add('MultiHit', 'You cannot place a hit on the same person twice in a row!')
term.Add('HitCooldown', 'This player died to a hit too recently.')
term.Add('BountyIncrease', 'You increased the bounty on # by #.')
term.Add('HitPlaced', 'You have placed a hit on # for #.')
term.Add('HitmanFailed', 'You have failed as a hitman!')
term.Add('HitmanKilledAll', 'It\'s your lucky day! That hitman was carrying the # bounty that was on your head.')
term.Add('Need911Reason', 'Please input a reason for your 911 call!')
term.Add('Canceled911', 'You\'ve canceled your 911 call.')

term.Add('EmployeeChangedJob', 'Your employee has changed jobs!')
term.Add('EmployeeChangedJobYou', 'Your employer\'s contract has been terminated because you changed jobs!')
term.Add('EmployeeLeft', 'Your employee has disconnected!')
term.Add('EmployerLeft', 'Your employer has disconnected!')
term.Add('PlayerNotHirable', '# is not hirable.')
term.Add('EmployeeTriedEmploying', 'You are seeking work currently. You cannot hire an employee!')
term.Add('AlreadyEmployed', 'You\'re already employed!')
term.Add('CannotAffordEmployee', 'You cannot affort to hire anyone!')
term.Add('EmployRequestSent', '# has been sent your request for hire.')
term.Add('SetHirePriceToHigh', 'You can\'t set your hire price higher than #!')
term.Add('SetHirePrice', 'You have set your hire price to #.')
term.Add('YouHired', 'You have hired # for #.')
term.Add('YouAreHired', '# has hired you for #.')
term.Add('EmployRequestDen', '# has denied your request for hire.')
term.Add('EmployeeFired', 'You have fired #.')
term.Add('EmployeeFiredYou', '# has fired you!')
term.Add('EmployeeQuit', '# has quit their job with you!')
term.Add('EmployeeQuitYou', 'You have quit for job for #.')

term.Add('CannotTool', 'Ваш ранг не может использовать инструмент "#"!')
term.Add('DupeRestrictedEnts', 'You cannot spawn dupes containing these entities!')
term.Add('DupeNeedsRepair', 'Your dupe has blacklisted models are entities in and will likely be broken. Click again within 5 seconds to paste it anyway.')
term.Add('DupeRemovedModel', '# blacklisted props and # constraints have been removed from your dupe.')
term.Add('WhitelistFull', 'The whitelist is full #/750')
term.Add('CacheFull', 'The model precache is full #/100!')
term.Add('PropWhitelisted', '# has been whitelisted by #.')
term.Add('PropBlacklisted', '# has been blacklisted by #.')
term.Add('UnsharedPropsYou', 'You have unshared your props with #.')
term.Add('UnsharedProps', '# has unshared their props with you.')
term.Add('OrgSharedProps', '# has shared their props with the org.')
term.Add('OrgUnsharedProps', '# has unshared their props with the org.')
term.Add('SharedPropsYou', 'You have shared your props with #.')
term.Add('SharedProps', '# has shared their props with you.')
term.Add('PPGroupSet', '# has been set to group # by #.')
term.Add('PropNotWhitelisted', '# не в вайтлисте!')

term.Add('CannotDestroyWeapon', 'Вы не можете уничтожить это оружие!')

term.Add('YourEntDestroyed', 'Ваш # был уничтожен!')
term.Add('InvalidURL', 'Недействительный URL!')
term.Add('VideoFailed', 'Не удалось загрузить видео: #.')
term.Add('VideoTooLong', 'You cannot play videos over # minutes!')
term.Add('FoodLimitReached', 'You have reached the food limit!')
term.Add('BoughtFoodProduction', 'You have paid # for food production.')
term.Add('SoldFoodNoProf', 'You sold some food and made no profit.')
term.Add('SoldFood', 'You sold some food and made # profit.')
term.Add('BoughtFood', 'You have purchased food for #.')
term.Add('MicrowaveFoodType', 'Microwave set to #')
term.Add('ThereIsACook', 'There is a cook. You can\'t do this!')
term.Add('EmptyShipment', 'There is nothing in the shipment.')

term.Add('GCMessageLimit', 'Your message needs to be more than 1 character!')

term.Add('CantSuicideJail', 'You can\'t suicide in jail.')
term.Add('CantSuicideWanted', 'You can\'t suicide while wanted.')
term.Add('CantSuicideFrozen', 'You can\'t suicide while frozen.')
term.Add('CantSuicideLiveFor', 'You have too much to live for!')
term.Add('CantSuicideRestrained', 'You can\'t suicide while restrained.')
term.Add('YouSuicided', 'You have lost 5 karma for being a disgrace to your family.')

term.Add('CantPurchaseUpgrade', 'You cannot purchase this. #')

term.Add('RPItemBought', 'Вы приобрели # за #.')
term.Add('RPItemBoughtLimit', 'You bought #/# # for #.')

term.Add('CantAdminCleanup', 'You cannot use admin cleanup!')

term.Add('MayorHasDied', 'Мэр погиб!')
term.Add('YouWereBailed', '# внёс за вас залог!')

term.Add('AmmoLabProfit', 'You received $# from your ammo lab.')
term.Add('BoughtAmmo', 'You have bought ammo for $#.')
term.Add('AmmoLabExploded', 'Your ammo lab has exploded!')

term.Add('ArmorLabProfit', 'You received $# from your armor lab.')
term.Add('BoughtArmor', 'You have bought armor for $#.')
term.Add('ArmorLabExploded', 'Your armor lab has exploded!')

term.Add('ChequeFound', 'You have found # in a cheque made out to you from #.')
term.Add('ChequeMadeTo', 'This cheque is made out to #.')
term.Add('ChequeTorn', 'You have torn up the cheque.')
term.Add('MoneyFound', 'Вы нашли $#!')

term.Add('MustBeHobo', 'You need to be a hobo to use this!')
term.Add('AlreadyDisguised', 'You\'re already disguised!')
term.Add('GunLicenseActive', 'You have activated your gun license.')
term.Add('AlreadyHasGunLicense', 'You already have a gun license!')
term.Add('YouGotAIDS', 'You have contracted AIDS and will soon die.')
term.Add('YouGotHIV', 'You have contracted HIV from an exposed needle.')
term.Add('STDCured', 'You have cured your sexually tramsitted diseases.')
term.Add('PimpSTDCured', 'You have cured # of their sexually tramsitted diseases.')
term.Add('NowDisguised', 'You are now disguised as a #.')
term.Add('DisguiseWorn', 'Your disguise has worn off.')
term.Add('DisguiseLimit', 'You cannot disguise again for # minutes.')

term.Add('MedLabProfit', 'You received $# from your medic lab.')
term.Add('BoughtHealth', 'You have bought health for $#.')
term.Add('MedLabExploded', 'Your medic lab has exploded!')

term.Add('KeypadControlsX', 'This keypad controls # entities.')
term.Add('EntityControlledByX', 'This entity is controlled by # keypads.')

term.Add('VoteAlone', 'You have won the vote since you are alone in the server.')
term.Add('BannedFromJob', 'You are restricted from that job for #s. Reason: #.')
term.Add('BannedFromJobPerma', 'You are restricted from that job. Reason: #.')
term.Add('CantGoPolice', 'You were recently killed. You need to wait # seconds to go police.')
term.Add('VotedTooSoon', 'Please wait # more seconds before voting to become this job.')
term.Add('AlreadyThisJob', 'You\'re already this job!')
term.Add('JobLimit', 'Team limit has already been reached.')
term.Add('RegisteredForVote', 'You have registered for the upcoming vote!')
term.Add('AlreadyVoting', 'Voting has already begun. You\'re too late!')
term.Add('AdminRoomNotSet', 'The sit room location has not been set!')
term.Add('JobNeedsPlaytime', 'You need # hours play time or vip for this job!')
term.Add('JobNeedsAdmin', 'You must be moderator+ for this job.')
term.Add('JobNeedsSA', 'You must be SA+ for this job.')
term.Add('JobNeedsBanned', 'You need to be banned from the server to become this class.')
term.Add('JobNeedsManualSet', 'You need to be set to this job by an admin.')
term.Add('IncorrectJob', 'You are not currently the correct job to do that!')
term.Add('VoteStarted', 'Vote has been created.')
term.Add('CannotJob', 'You cannot change your job right now.')
term.Add('JobLenShort', 'Jobs must be more than # characters.')
term.Add('JobLenLong', 'Jobs must be less than # characters.')

term.Add('CannotPurchaseItem', 'You\'re not allowed to purchase this item.')
term.Add('ItemUnavailable', 'That item is unavailable.')
term.Add('UnableToItem', 'You were unable to purchase that item.')
term.Add('ShipmentCooldown', 'Please wait before spawning another shipment.')

term.Add('MedicExists', 'You cannot buy health because there are medics.')
term.Add('HealthIsFull', 'Your health is full already!')

term.Add('CannotDropWeapon', 'You cannot drop this weapon!')
term.Add('LookAtEntity', 'You need to be looking at an entity!')
term.Add('CannotSetPrice', 'You cannot set the price of this entity!')

term.Add('AnalProlapse', 'You have overexerted your anus and died from anal prolapse.')
term.Add('NoMorePoo', 'You have no more poo left!')
term.Add('NotARapist', 'You are not a rapist.')
term.Add('RapeSOD', 'You cannot rape Staff on Duty.')
term.Add('RapeFailed', 'Rape attempt failed!')
term.Add('RapeAttempted', 'Someone has attempted to intrude your butthole.')
term.Add('Raped', 'You have intruded #\'s butthole.')
term.Add('YouAreRaped', 'Someone has intruded your butthole.')
term.Add('AnalProlapseShort', 'You have died from anal prolapse.')
term.Add('DickFellOff', 'Your dick has fallen off.')
term.Add('NoRangeOfMotion', 'You lack the range of motion to rape right now.')
term.Add('RapeStruggled', 'You struggled free from rape!')
term.Add('RapeVictimStruggled', 'Your victim struggled free!')

term.Add('CannotVote', 'You cannot vote.')
term.Add('FoundNothing', 'You found nothing.')
term.Add('RobberyAttempt', 'You felt a slight movement in your pocket.')
term.Add('YouRobbed', 'You have stolen $#!')
term.Add('YouAreRobbed', 'Your wallet feels lighter.')
term.Add('YouRobbedItem', 'You pulled out an item. Grab it fast!')
term.Add('YouAreRobbedItem', 'Your pocket feels lighter.')

term.Add('NoteUpdated', 'Текст записки обновлён.')
term.Add('USENote', 'Используйте E чтобы изменить текст записки.')

term.Add('OrgYouAreStuck', 'You\'re stuck! >:)')
term.Add('OrgYourRank', '# has set your rank to \'#\'.')
term.Add('OrgSetRank', '# has been set to \'#\'.')
term.Add('OrgUnknownRank', 'Unknown rank \'#\'.')
term.Add('OrgRankRename', 'Rank \'#\' renamed to \'#\'.')
term.Add('OrgReorderLimit', 'You cannot reorder the highest and lowest ranks.')
term.Add('OrgRankUpdated', 'Rank \'#\' updated.')
term.Add('OrgMaxRanks', 'Maximum ranks reached.')
term.Add('OrgRankCreated', 'Rank \'#\' created.')
term.Add('OrgDeleteLimit', 'You cannot delete the top and bottom ranks.')
term.Add('OrgRankDelete', 'Rank \'#\' removed.')
term.Add('OrgBannerUpdated', 'Banner updated.')
term.Add('OrgPlayerInvited', 'You invited # for $#.')

term.Add('SetOutfit', 'Your outfit has been set to #')

-- Stools
term.Add('CantMetagameKeypad', 'You must use a keypad for your fading door!')
term.Add('FadeDoorCreated', 'Fading door created.')
term.Add('FadeDoorCreatedExtra', 'Fading door created. Now, right click again to place a keypad.')
term.Add('InvalidPassword', 'Invalid password!')
term.Add('KeypadHoldLength', 'The hold length must be at least # seconds.')
term.Add('NoCollidedWorld', 'World collisions disabled.')
term.Add('CollidedWorld', 'World collisions enabled.')
term.Add('NoCollided', 'Коллизия выключена.')
term.Add('Collided', 'Коллизия включена.')
term.Add('UnBreakable', 'Неуязвимость включена.')
term.Add('Breakable', 'Неуязвимость выключена.')
term.Add('ColorizedYou', 'Ваш цвет был изменён.')
term.Add('DecolorizedYou', 'Ваш цвет был сброшен')
term.Add('ColorizedPlayer', 'Перекрашен #.')
term.Add('DecolorizedPlayer', 'Сброшен цвет у #.')
term.Add('DecolorizedAll', 'Сброшен цвет у всех.')
term.Add('FadingDoorAdded', 'Linked prop to fading door.')
term.Add('FadingDoorRemoved', 'Unlinked prop from fading door.')
term.Add('FadingDoorOnlyProps', 'Only props can be made into fading doors!')
term.Add('FadingDoorMaxProps', 'You\'re only allowed to make # props into one fading door!')
term.Add('FadingDoorNoProps', 'Right click a prop to link it before you make a pad!')

-- Sandbox
term.Add('SboxXLimit', 'Вы достигли лимита # #!')
term.Add('SboxSpawned', 'Заспавнено #/# #.')

-- Entities folder
term.Add('ImageNSFW', 'Эта картинка была отмечена как непотребная. Пожалуйста используйте другую.')

term.Add('PlayerTaserResistance', '# получил неприкосновенность и на этот раз не пострадал от электрошокера!')
term.Add('PlayerTaserResistanceSelf', 'Вы были поражены электрошоком, но получили неприкосновенность и на этот раз не пострадали!')

term.Add('ArcadeMachineUse', 'Get ready to play!')
term.Add('PlayerNotInJail', '# не в тюрьме.')
term.Add('PlayerFuckedBailing', 'Ты придурок, копы уже у тебя на хвосте!')
term.Add('PlayerBailedPlayer', 'Вы внесли залог за # в размере # и получили # кармы.')
term.Add('PlayerTookDonationBox', 'Вы забрали #.')
term.Add('YouDontOwnThis', 'Вы не владеете этим!')
term.Add('PlayerReceivedDonationBox', 'Кто-то положил # в вашу коробку для пожертвований.')
term.Add('PlayerNotWanted', 'Этот игрок не в розыске!')
term.Add('PlayerTookMoneyBasket', 'Вы забрали #.')
term.Add('PrinterIsFull', 'Этот принтер уже заправлен!')
term.Add('PrinterRefilled', 'Вы заправили принтер за #.')
term.Add('PlayerSoldDrugs', 'Вы продали # за #.')

term.Add('SoldItem', 'You sold a item and made # profit and gained # karma.')
term.Add('BoughtItem', 'Вы приобрели предмет за #.')

term.Add('GamblingMachinePlayerCannotAfford', 'You cannot afford to play this # machine!')
term.Add('GamblingMachineHouseCannotAfford', 'You cannot afford your # machine! It is now out of service.')
term.Add('GamblingMachineOwnerCannotAfford', 'The owner of this # machine can no longer afford to operate. It is now out of service.')
term.Add('GamblingMachineInService', 'Your # machine is now in service.')
term.Add('GamblingMachineIOutService', 'Your # machine is now out of service.')

term.Add('5050PlayerWin', 'Вы выиграли # играя в FiftyFifty!')
term.Add('5050PlayerLose', 'Вы проиграли # играю FiftyFifty!')
term.Add('5050Tie', 'You tied and got your money back.')

term.Add('BasicSlotsPlayerWin', 'You won # playing Basic Slots!')
term.Add('BasicSlotsPlayerLose', 'You lost # playing Basic Slots!')

term.Add('SpinWheelPlayerWin', 'You won # playing Spin Wheel!')
term.Add('SpinWheelPlayerLose', 'You lost # playing Spin Wheel!')

term.Add('AlreadyHaveWeapon', 'You already have this weapon equipped! Use your pocket.')

term.Add('BiometricAddedAccess', 'Added # to scanner')
term.Add('BiometricRemovedAccess', 'Removed # from scanner')
term.Add('BiometricToggledOrgOwn', 'Toggled org ownership')
term.Add('BiometricCopiedSettings', 'Copied settings to # scanners')

term.Add('TollMadeProfit', 'You made # (# has been taxed) from your toll.')

term.Add('YourItemLabRanOut', 'Your item lab has ran out!')

-- Weapons folder
term.Add('ArrestBatonBonus', 'You have received a # bonus and # karma for destroying this illegal entity.')
term.Add('ArrestBatonArrested', 'You\'ve been arrested by #.')
term.Add('ArrestBatonYouArrested', 'You arrested #.')
term.Add('PlayerRangDoorbell', 'Someone has rang your doorbell.')
term.Add('KeysCooldown', 'The lock on this door is busted! Try again in # seconds!')
term.Add('UnarrestBatonTarg', 'You\'ve been unarrested by #.')
term.Add('UnarrestBatonOwn', 'You unarrested #.')

term.Add('ApparelPurchased', 'You have purchased # for #.')
term.Add('ApparelEquiped', '# equipped!')
term.Add('ApparelRemoved', '# removed!')

term.Add('BURGHungerImmune', 'You\'re immune to hunger until you die, now!')
term.Add('BURGNotPeople', 'Silly burger, burgers aren\'t people!')

term.Add('CannotPocket', 'You cannot put # in your pocket!')
term.Add('CannotPocketCooldown', 'You need to wait # seconds before you can pocket this!')
term.Add('CannotPocketUsedShipments', 'Merchant classes cannot pocket partially full shipments!')

-- Kombat
term.Add('KombatFull', 'Sorry, all # slots for Kombat have been filled already.')
term.Add('KombatMissedDeadline', 'Sorry, you\'ve missed the deadline to sign up for Kombat.')
term.Add('KombatRestrained', 'Sorry, you cannot enter Kombat while restrained.')
term.Add('KombatCarrying', 'Sorry, you cannot enter Kombat while carrying someone.')

-- Gun Lab
term.Add('ItemLabRefilled', 'You\'ve filled this Lab for $#. It now has # metal.')
term.Add('ItemLabCrafting', 'Used # metal to begin crafting #.')

-- Bodygroups
term.Add('ModelNoBodyGroups', 'This model does not contain any preset bodygroups.')
term.Add('BodyGroupPermission', 'You do not have permission to set bodygroups on this model/player.')
term.Add('BodyGroupNotFound', 'The bodygroup "#" was not found for this model.')
term.Add('BodyGroupSet', 'Bodygroup set to "#".')
