term.Add('AdminPasswordTooShort', 'The reset key must be at least # characters long.')
term.Add('AdminPasswordReset', '# has reset #\'s admin password')
term.Add('AdminPasswordRequest', 'Пожалуйста введите ваш пароль.')
term.Add('AdminPasswordResetRequest', 'Пожалуйста введите новый пароль.')
term.Add('AdminPasswordIsReset', 'Your password has been reset.')
term.Add('AdminPasswordSet', 'Ваш пароль был установлен.')
term.Add('AdminNowAuthenticated', 'Вы теперь авторизованы.')
term.Add('AdminPasswordIncorrect', 'Неверный пароль.')
term.Add('AdminPasswordResetCodeIncorrect', 'That reset code was incorrect.')
