term.Add('AdminPasswordTooShort', 'The reset key must be at least # characters long.')
term.Add('AdminPasswordReset', '# has reset #\'s admin password')
term.Add('AdminPasswordRequest', 'Please enter your password.')
term.Add('AdminPasswordResetRequest', 'Please set a new password.')
term.Add('AdminPasswordIsReset', 'Your password has been reset.')
term.Add('AdminPasswordSet', 'Your password has been set.')
term.Add('AdminNowAuthenticated', 'You\'re now authenticated.')
term.Add('AdminPasswordIncorrect', 'That password was incorrect.')
term.Add('AdminPasswordResetCodeIncorrect', 'That reset code was incorrect.')