term.Add('AdminPasswordTooShort', 'The reset key must be at least # characters long.')
term.Add('AdminPasswordReset', '# has reset #\'s admin password')
term.Add('AdminPasswordRequest', 'Пожалуйста введите ваш пароль.')
term.Add('AdminPasswordResetRequest', 'Please set a new password.')
term.Add('AdminPasswordIsReset', 'Your password has been reset.')
term.Add('AdminPasswordSet', 'Your password has been set.')
term.Add('AdminNowAuthenticated', 'Вы теперь авторизованы.')
term.Add('AdminPasswordIncorrect', 'Неверный пароль.')
term.Add('AdminPasswordResetCodeIncorrect', 'That reset code was incorrect.')
