term.Add('PlayerFirstConnect', '# подключился к серверу. (Впервые).')
term.Add('PlayerConnect', '# подключился к серверу. (Последний визит - #).')
term.Add('PlayerDisconnect', '# отключился от сервера.')

term.Add('RankExpired', 'Ваш ранг истекает #.')

term.Add('WaitBeforCommand', 'Подождите # секунд перед использованием "#" ещё раз!')
term.Add('InvalidCommand', '# неверная команда!')
term.Add('NeedFlagToUseCommand', 'Вам нужен флаг "#" чтобы использовать #')
term.Add('MissingArg', 'Вы забыли указать: #')
term.Add('FatalError', 'Ошибка во время выполнения команд.')
term.Add('TriedToRunCommand', '# пытался использовать команду # на вас!')
term.Add('SameWeight', 'Вы не можете использовать команду на админа старше или вашего ранга!')
term.Add('InvalidTimeUnit', 'Неверная единица времени. Пожалуйста, используйте количество единиц с последующей единицы типа (mi, h, d, w, mo)')
term.Add('InsufficientImmunity', 'Your rank is not high enough to perform actions including #.')
